### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by mrakgr** [Theano/libgpuarray#172]
I've followed the instructions and installed the latest Cmake, but I can't figure out how to build `libgpuarray` properly. Could anybody take a look and tell me what these error messages mean?

```
C:\libgpuarray\Build>cmake .. -DCMAKE_BUILD_TYPE=Release
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5 (found version "7.5")
-- Could NOT find OpenCL (missing:  OPENCL_LIBRARIES)
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - not found
-- Looking for cublasSgemmEx
-- Looking for cublasSgemmEx - not found
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Checking for one of the modules 'check'
Tests disabled because Check was not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "gpuarray" in directory C:/libgpuarray/src
```

**Comment by mrakgr** [comment]
Actually, despite the above error messages, I managed to build with VC++ and then MingW just fine. This is surprising. I suppose I can just put the `.dll` and the `.a` library files into the MingW lib directory. Does Theano use the dlls or static libraries?

**Comment by mrakgr** [comment]
Ok, I got a bit further in, but I am still facing errors. This is my current best attempt.

```
C:\libgpuarray>python setup.py build_ext -L C:\libgpuarray\lib -I C:\libgpuarray\include
running build_ext

C:\libgpuarray>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pygpu.egg-info\requires.txt
writing pygpu.egg-info\PKG-INFO
writing top-level names to pygpu.egg-info\top_level.txt
writing dependency_links to pygpu.egg-info\dependency_links.txt
reading manifest file 'pygpu.egg-info\SOURCES.txt'
writing manifest file 'pygpu.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\blas.pyd -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\dtypes.py -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\elemwise.py -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\gpuarray.pyd -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\operations.py -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\reduction.py -> build\bdist.win-amd64\egg\pygpu
creating build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\main.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\support.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_blas.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_elemwise.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_gpu_ndarray.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_operations.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_reduction.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\test_tools.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tests\__init__.py -> build\bdist.win-amd64\egg\pygpu\tests
copying build\lib.win-amd64-2.7\pygpu\tools.py -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\_array.py -> build\bdist.win-amd64\egg\pygpu
copying build\lib.win-amd64-2.7\pygpu\__init__.py -> build\bdist.win-amd64\egg\pygpu
byte-compiling build\bdist.win-amd64\egg\pygpu\dtypes.py to dtypes.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\elemwise.py to elemwise.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\operations.py to operations.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\reduction.py to reduction.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\main.py to main.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\support.py to support.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_blas.py to test_blas.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_elemwise.py to test_elemwise.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_gpu_ndarray.py to test_gpu_ndarray.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_operations.py to test_operations.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_reduction.py to test_reduction.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\test_tools.py to test_tools.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tests\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\tools.py to tools.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\_array.py to _array.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\__init__.py to __init__.pyc
creating stub loader for pygpu\gpuarray.pyd
creating stub loader for pygpu\blas.pyd
byte-compiling build\bdist.win-amd64\egg\pygpu\gpuarray.py to gpuarray.pyc
byte-compiling build\bdist.win-amd64\egg\pygpu\blas.py to blas.pyc
installing package data to build\bdist.win-amd64\egg
running install_data
copying pygpu\gpuarray.h -> build\bdist.win-amd64\egg\pygpu
copying pygpu\gpuarray_api.h -> build\bdist.win-amd64\egg\pygpu
copying pygpu\blas_api.h -> build\bdist.win-amd64\egg\pygpu
copying pygpu\numpy_compat.h -> build\bdist.win-amd64\egg\pygpu
creating build\bdist.win-amd64\egg\EGG-INFO
copying pygpu.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pygpu.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pygpu.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pygpu.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pygpu.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
pygpu.__init__: module references __file__
pygpu.tests.main: module references __file__
creating 'dist\pygpu-0.2.1-py2.7-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pygpu-0.2.1-py2.7-win-amd64.egg
removing 'c:\users\marko\anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg' (and everything under it)
creating c:\users\marko\anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg
Extracting pygpu-0.2.1-py2.7-win-amd64.egg to c:\users\marko\anaconda2\lib\site-packages
pygpu 0.2.1 is already the active version in easy-install.pth

Installed c:\users\marko\anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg
Processing dependencies for pygpu==0.2.1
Searching for Mako==1.0.4
Best match: Mako 1.0.4
Adding Mako 1.0.4 to easy-install.pth file
Installing mako-render-script.py script to C:\Users\Marko\Anaconda2\Scripts
Installing mako-render.exe script to C:\Users\Marko\Anaconda2\Scripts

Using c:\users\marko\anaconda2\lib\site-packages
Searching for MarkupSafe==0.23
Best match: MarkupSafe 0.23
Adding MarkupSafe 0.23 to easy-install.pth file

Using c:\users\marko\anaconda2\lib\site-packages
Finished processing dependencies for pygpu==0.2.1

C:\libgpuarray>python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pygpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygpu\__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu\elemwise.py", line 5, in <module>
    from .tools import ScalarArg, ArrayArg, as_argument, check_contig, check_args, lru_cache
  File "pygpu\tools.py", line 10, in <module>
    from .dtypes import dtype_to_ctype, _fill_dtype_registry
  File "pygpu\dtypes.py", line 6, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray

```

This it is using libraries compiled by MingWpy, though I will try the VS ones next. I am not sure why the above is failing now.

**Comment by mrakgr** [comment]
Found that `libgpuarray` does not have an `include` directory, but `src` instead. Though even if I pass that as include it still fails to work correctly and gives me the cannot import name gpuarray.

**Comment by abergeron** [comment]
It's looking for the dll in the normal windows path which is %PATH%.

You can either find a directory on that path (like anaconda2\lib) and drop the dll in or make the directory they are in part of the path.  Note that exporting PATH does not work.  You have to set PATH in the system properties.

It is possible that it find libgpuarray.so but does not find one of the dependant modules.  I only support MSVC because I know dependencies resolution works ok.  Maybe it does for MinWpy, I have no idea.

Also I'm curious about where you found a libgpuarray.py file since there are none in the distribution.

**Comment by mrakgr** [comment]
```

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include>where libgpuarray.dll
C:\libgpuarray\lib\libgpuarray.dll
C:\Users\Marko\Anaconda2\share\mingwpy\lib\libgpuarray.dll

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include>python
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pygpu
pygpu.gpuarray
C:\Users\Marko\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\gpuarray.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Marko\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\__init__.py", line 7, in <module>
    from . import gpuarray
  File "C:\Users\Marko\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\gpuarray.py", line 9, in <module>
    __bootstrap__()
  File "C:\Users\Marko\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\gpuarray.py", line 8, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
ImportError: DLL load failed: The specified module could not be found.
```
Essentially, the first `where libgpuarray.dll` command proves that the dll file is in path. Ignore that I am using it from the Cuda directory, I was just finishing up configuring Theano when I noticed your message. 

As for `libgpuarray.py`, it is in `C:\Users\Marko\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\gpuarray.py`. It gets installed there using `python setup.py install`.

One thing that I wanted to try is using the `""` quotes for include and library paths when calling `build_ext`. The idea occurred to me just now.

**Comment by mrakgr** [comment]
Ah, I see it! VS produces `gpuarray.dll` while MingW produces `libgpuarray.dll`. Now it loads properly.

**Comment by JonnoFTW** [comment]
I'm having the exact same problem, I built libgpuarray with vs2015, but no matter where I place the generated gpuarray.dll file, python always complains that it can't be loaded.

**Comment by mrakgr** [comment]
This has been a while, and I ended not even using Theano in favor of my own library, and there was a crash bug in the new backend on Windows that I have no idea whether it has been fixed by now...but if were to venture a guess did you try adding something like `C:\libgpuarray\lib` where the `gpuarray.dll` is supposed to be to PATH? Maybe that could be it.

Also back then, I wrote a little [guide on installing Theano](https://github.com/mrakgr/Tutorials/blob/master/theano_install.md) that might be of use to you.

**Comment by JonnoFTW** [comment]
Windows has found `gpuarray.dll`, here's the output:

```
C:\Users\Jonathan>where gpuarray.dll
C:\Program Files\libgpuarray\bin\gpuarray.dll

C:\Users\Jonathan>python -c "import pygpu"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
ImportError: DLL load failed: The specified module could not be found.

```

**Comment by JonnoFTW** [comment]
Actually I fixed it by adding the build location (`C:\Users\Jonathan\Documents\GitHub\libgpuarray\lib\Release`) to my `path`, perhaps the install script doesn't properly copy everything over #264
