### ISSUE TITLE
Import error due to missing `nose` package

### ISSUE THREAD

**Issue by kohr-h** [Theano/libgpuarray#202]
On a system without `nose`, one gets the following error when trying to import `pygpu`:

``` python
>>> import pygpu
Traceback (most recent call last):
[...]
File "[...]/pygpu/__init__.py", line 15, in <module>
    from .tests import main

  File "[...]/pygpu/tests/main.py", line 2, in <module>
    import nose.plugins.builtin

ImportError: No module named 'nose'
```

Now `nose` is not mentioned in `setup.py` as dependency, and from [the code](https://github.com/Theano/libgpuarray/blob/fc7a592ab528e28bf13ba5683c5aa37510ba716c/pygpu/__init__.py#L16-L21) I conclude that this is intentional. Unfortunately, the code that raises an error if one tries the tests without `nose` is never reached.

You could simply fence the `from . import main` with `try...except ImportError`, but that is a bit ugly since you suddenly cannot rely on `pygpu.test.main` to exist at all. Alternatively, you could export an availability flag, something like

``` python
# in pygpu/test/main.py
try:
    import nose.plugins.builtin

    from nose.config import Config
    from nose.plugins.manager import PluginManager
    NOSE_AVAILABLE = True
    from numpy.testing.nosetester import import_nose, NoseTester
    from numpy.testing.noseclasses import KnownFailure, NumpyTestProgram
except ImportError:
    NoseTester = object
    NOSE_AVAILABLE = False

# ---------------------------------------
# in pygpu/__init__.py
from .tests import main
if main.NOSE_AVAILABLE:
    test = main.NoseTester().test
else:
    def test():
        raise ImportError("The nose module is not installed."
                          " It is needed for pygpu tests.")

# ---------------------------------------
# in other files under pygpu/test
try:
    import nose  # or related
except ImportError:
    pass


```

**Comment by abergeron** [comment]
Fixed in 0.6.5
