### ISSUE TITLE
Error When Importing pygpu: libgpuarray.so: undefined symbol: cuEventDestroy_v2

### ISSUE THREAD

**Issue by JonnoFTW** [Theano/libgpuarray#258]
When I try to import `pygpu` I get the following error:
```
$ python -c "import pygpu"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
ImportError: /home/mack0242/tools/lib/libgpuarray.so: undefined symbol: cuEventDestroy_v2
```

I compiled my libgpuarray using: 
```
cmake -DCMAKE_INSTALL_PREFIX=/home/mack0242/tools \
           -DCMAKE_BUILD_TYPE=Release \
           -DCHECK_INCLUDE_DIRS=/home/mack0242/tools/include \
           -DCHECK_LIBRARIES=/home/mack0242/tools/lib \
           -DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/libcudart.so \
           -DCUDA_LIBRARIES=/usr/local/cuda/lib64/  ..
```
The extra lines are there because it couldn't find `check`, even though I added `~/tools/lib/pkgconfig/` to `$PKG_CONFIG_PATH`. Without `-DCUDA_CUDA_LIBRARY` I get the output from cmake:

```
-- The C compiler identification is GNU 4.8.2
-- Check for working C compiler: /opt/rh/devtoolset-2/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-2/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "7.5") 
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Found NCCL: /home/mack0242/tools/lib/libnccl.so  
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Building with NVRTC
-- Looking for cublasSgemmEx
-- Looking for cublasSgemmEx - found
-- Building with NCCL
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- Checking for one of the modules 'check'
-- Looking for ck_assert_ptr_ne
-- Looking for ck_assert_ptr_ne - not found
Tests disabled because Check was not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "gpuarray-static" in directory /tmp/mack0242py/libgpuarray/src
    linked by target "gpuarray" in directory /tmp/mack0242py/libgpuarray/src

-- Configuring incomplete, errors occurred!
```

**Comment by JonnoFTW** [comment]
`CUDA_CUDA_LIBRARY` was set incorrectly, it should have been `/usr/local/cuda/lib64/stubs/libcuda.so`
