### ISSUE TITLE
Add windows install instructions

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#264]
Currently the INSTALL file says: "I have no idea how to install on Windows.", not very helpful.

For me the following steps were enough to install libgpuarray:

* Clone the library
* Create build folder, open CMake gui
* Change `CMAKE_INSTALL_PREFIX` to `libgpuarray/lib`. Perhaps this should be default on windows.
* Open the .sln file with Visual Studio
* Build the INSTALL package (needs PR #263)
* Manually move the dll's to somewhere in the PATH. Perhaps we should automate this on windows.
* Build the Cython extension (in the libgpuarray root) with: `python setup.py build_ext --compiler=msvc`
* Install the package with `python setup.py install`

Now everything works.

Should we add instructions for this somewhere, if so, where?

**Comment by abergeron** [comment]
If you want to update the documentation with these instructions, I will be very open to this.  They should go in doc/installation.rst

**Comment by Iceman121** [comment]
Hey I'm having trouble building the INSTALL package. Getting the following errors (using Visual Studio 2013):
```
Error	15	error C2057: expected constant expression	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray
Error	16	error C2466: cannot allocate an array of constant size 0	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray
Error	17	error C2133: 'pInd' : unknown size	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray
Error	32	error C2057: expected constant expression	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray-static
Error	33	error C2466: cannot allocate an array of constant size 0	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray-static
Error	34	error C2133: 'pInd' : unknown size	C:\gpuarray\libgpuarray\src\util\integerfactoring.c	830	1	gpuarray-static
Error	35	error MSB3073: The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	INSTALL
```

Any idea why I am facing this and what I can do to resolve?

Thanks.

**Comment by abergeron** [comment]
There was some unsupported code for MSCV in a recent PR.  This has been fixed and the master should work now.

**Comment by Iceman121** [comment]
Hey, I tried building again with the fixed version, got the following error:
```
Error	969	error LNK2019: unresolved external symbol snprintf referenced in function gaIFLsnprintf	C:\libgpuarray-master\libgpuarray-master\Build\src\integerfactoring.obj	gpuarray
Error	970	error LNK1120: 1 unresolved externals	C:\libgpuarray-master\libgpuarray-master\lib\Debug\gpuarray.dll	gpuarray
Error	971	error MSB3073: The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	INSTALL
```

**Comment by abergeron** [comment]
Ok, we need to remove the call to snprintf also.

**Comment by Iceman121** [comment]
Okay, please let me know when it is ready to clone. Thanks.

**Comment by abergeron** [comment]
There is this #275.

I don't know when someone will have time to review.

**Comment by nouiz** [comment]
I merged it.

**Comment by Iceman121** [comment]
So good news, I was able to build successfully. 

I point out some steps to add to windows installation.
1. The INSTALL package needs to be built with admin privileges in release mode. So this needs to be built in the Visual Studio Developer Command Prompt with "msbuild libgpuarray.sln /p:Configuration=Release"
2. Restart is necessary after installing pygpu

I should point out that I tried running theano after this, but the kernel crashed. However, when I changed the device = gpu0 in the .theanorc.txt file from device = cuda, it worked just fine.

Thank you for all your help. You guys are great!

**Comment by adler-j** [comment]
Great, I'll try to get to writing these instructions sometime soon.

**Comment by nouiz** [comment]
device=gpu use the old backend. So the crash still need to be fixed.

**Comment by nouiz** [comment]
Just to note that we are working on conda packages. This will probably be the only supported way to install it for user. We can't support all combination of compiler on all platform we have.

**Comment by nouiz** [comment]
So mostly, this issue is about adding install instruction with conda on windows. Not the full installation.

**Comment by adler-j** [comment]
Any update on the conda packages?

**Comment by nouiz** [comment]
"conda install -c rdonnelly libgpuarray" or "conda install -c rdonnelly pygpu" should install the last release of libgpuarray 0.6.2

**Comment by michaelklachko** [comment]
I ran both of these conda commands on Windows 10 and Theano 0.9.0 and it seemed like both had installed successfully. Then I changed my theanorc.txt file from device=gpu0 to device=cuda, and I got the following error:

import theano
ERROR:theano.gpuarray:Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "c:\Theano\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Error loading library: 0

**Comment by michaelklachko** [comment]
I updated my CUDA from 7.5 to 8.0, and the error changed to:
```

In [1]: import theano
ERROR:theano.gpuarray:Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "c:\Theano\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "c:\Theano\theano\gpuarray\dnn.py", line 177, in dnn_available
    if not dnn_present():
  File "c:\Theano\theano\gpuarray\dnn.py", line 168, in dnn_present
    dnn_present.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudnn
collect2.exe: error: ld returned 1 exit status
```


It works fine when I use device=gpu0. 
Here's my theanorc file:
```

[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

[nvcc]
flags=-LC:\Anaconda\libs
fastmath=True
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

[global]
device = cuda
floatX = float32
warn_float64=warn
int_division=raise
print_active_device = True
optimizer_including = cudnn
allow_gc = False
assert_no_cpu_op=warn
warn.round=False

[lib]
cnmem = 0.4

[dnn]
enabled = True

include_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include
library_path=C:/Program Files/NVIDIA GPU Computing Toolkit\CUDA/v8.0/lib
```

**Comment by nouiz** [comment]
Theano isn't able to find cudnn and you forced to use it:


[dnn]
enabled = True

Remove that or put cudnn in a place where Theano will find it.

**Comment by michaelklachko** [comment]
Fred, 

Theano can find cudnn, because it works fine when I use device=gpu0:
`Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 40.0% of memory, cuDNN 5110)`

This error appears only when I switch to device=cuda, after installing libgpuarray and pygpu with conda commands. Is there anything else I should have done in addition to the conda commands? 

Here are the details of my setup: Anaconda (Python 2.7) on Windows 10, Mingw64, Visual Studio Community 2013, CUDA 8.0.61, CuDNN 5.1 (copied all 3 files to the corresponding locations in CUDA v8.0 folder). I updated Theano to 0.9.0 with git pull and python setup.py develop command. 

Again, this problem is specific to gpuarray. The old backend works fine, and can see the cudnn files.

**Comment by notoraptor** [comment]
Hello ! About this line:
```
library_path=C:/Program Files/NVIDIA GPU Computing Toolkit\CUDA/v8.0/lib
```
Do you find the file `cudnn.lib` into the folder pointed by libray_path ? Maybe the file is in `library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64` instead (i.e `lib\x64` instead of just `lib`) ?

**Comment by michaelklachko** [comment]
Interesting! When I add \x64 to the library_path the python session crashes!
```
In [1]: import theano
Kernel died, restarting
```
If I completely remove both lines (library_path and include_path) from theanorc, the error stays the same:
`c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudnn`

The old backend can see cudnn files even without those lines.

**Comment by notoraptor** [comment]
Strange. I'm not used to spyder, could you check if the crash (`kernel died, restarting`) occurs in Python console ?

Also, which version of GCC (Mingw64) do you use ? With conda, the recommended package is `m2w64-toolchain` (`conda install m2w64-toolchain`).

**Comment by michaelklachko** [comment]
It happens in IPython console. Actually, Windows reports "Application Crashed" message when this happens, but Spyder keeps running after the kernel restart.

I installed Mingw64 outside of Anaconda, gcc version is 4.8. 

If the best way to solve this issue is to reinstall things, what should I reinstall, and in what order?

**Comment by notoraptor** [comment]
Hello, could you try to install the recommended GCC package for conda and then retry ?

```batch
REM Activate your conda env in which you installed theano
REM If you use the default conda env (i.e. root), run `activate root`, 
REM so that conda configures all environment variables correctly.
activate YOUR_CONDA_ENV

REM install m2w64-toolchain
conda install m2w64-toolchain

REM Then test again
```

**Comment by michaelklachko** [comment]
I don't use conda environments. Does it matter? 
If I install a new version of gcc, would it cause a compatibility issues? I've heard that I should use the same compiler that was used when I installed theano. I don't mind reinstalling everything, just want to do it right.

**Comment by notoraptor** [comment]
If you don't use conda environments, then your default environment should be named "root", so you must still run `activate root`.

If you install the recommended GCC package into a conda environment, then it will be available only when you activate that environment. Otherwise your default GCC installation will still remain available.

```batch
REM Outside conda, your default GCC (Mingw64) is available.

activate root

REM Inside conda, the installed conda-specific GCC is available.

deactivate

REM We're outside conda now, back to your default GCC.
```

I think compatibility issues you heard is more related to libgpuarray compilation issues, but that step is already done when you use conda pygpu package (as libgpuarray is already compiled).

So, inside the conda env (even root), everything should be safe.

**Comment by michaelklachko** [comment]
Ok, here's what I did:

```
C:\WINDOWS\system32>activate root

(root) C:\WINDOWS\system32>conda install m2w64-toolchain
<installed successfully>

(root) C:\WINDOWS\system32>python C:\Users\Michael\Desktop\Research\Code\strided_convnet.py
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "c:\Theano\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "c:\Theano\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "c:\Theano\theano\gpuarray\dnn.py", line 177, in dnn_available
    if not dnn_present():
  File "c:\Theano\theano\gpuarray\dnn.py", line 168, in dnn_present
    dnn_present.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
C:/Anaconda/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudnn
collect2.exe: error: ld returned 1 exit status
```

**Comment by notoraptor** [comment]
With `lib/x64` instead of `lib` in theanorc ?

**Comment by michaelklachko** [comment]
Ok, after adding \x64 it works, but only from windows command line, and only when I activate root environment:
```
(root) C:\WINDOWS\system32>python C:\Users\Michael\Desktop\Research\Code\strided_convnet.py
Using cuDNN version 5110 on context None
Mapped name None to device cuda: GeForce GTX TITAN X (0000:01:00.0)
```

If I run it in Spyder, it crashes the kernel. Should I update Mingw64 system wide?

**Comment by notoraptor** [comment]
Ok ! Yes, when I have talked about "Python console", I was thinking to default Python (not **I**Python).

Activating root is necessary to use the specific conda GCC.

Even if you update Mingw64 system wide, I think it will not help, because:
 * You may not get the same version as in conda.
 * The conda GCC may have been specifically compiled to work correctly with conda Python.
 * I don't know a way to install conda GCC at system wide. The only one method I know is to activate conda env if you want to use the conda GCC.

Unfortunately, I can't help for spyder as I don't use this software.

**Comment by michaelklachko** [comment]
I see. Do you have any guess as why it works with the old backend, but crashes with the new one? 

I can launch Spyder from the root environment, and then it works fine, however, this solution is still not ideal for me, because installing mingw64-toolchain with conda forced downgrade of many packages, for example numpy went from 1.12 to 1.10, and most importantly Spyder went from 3.1 to 2.3. 
Can you think of any alternatives to setting it all up on Windows, which would allow me to use latest versions of numpy and Spyder, and use gpuarray with Theano?

**Comment by notoraptor** [comment]
That's very strange, because I have NumPy 1.12 with m2w64-toolchain installed and theano last version, and all works on my computer.

What I can suggest is to create a new conda environment from scratch, then install things and check if all runs correctly. This will have no incidence neither on your conda root environment nor on system. Keep your theanorc as it is currently.

```batch

REM Create a new conda env named "python2" with python 2.7
conda create -n python2 python=2

REM activate python2
activate python2

REM Then install basic required packages for Theano
conda install numpy scipy mkl-service libpython m2w64-toolchain

REM Now install theano and pygpu
conda install theano pygpu

REM And check if all is OK.
python -c "import theano, pygpu, numpy; print(theano.__version__, pygpu.__version__, numpy.__version__);"

REM If all is OK, consider using this conda env ("python2") for your works.
REM You can deactivate it at anytime:
deactivate

REM If you want to delete the env, be sure it is deactivated and then run:
conda remove --all -n python2
```

For the moment I don't know why it works well with old back-end but not with the new one. Maybe further investigations will be necessary.

**Comment by michaelklachko** [comment]
Ok, everything is good now. I uninstalled Anaconda, Mingw64 and Theano from my machine, then installed everything using conda (not using environments). There were no issues. 
The speedup with gpuarray backend: my convnet training time went from 19.2 min to 17.3 min on Maxwell Titan X. Not bad.

Thank you so much for your help!

**Comment by jingweimo** [comment]
@michaelklachko : I probably come across same issue with you when I update the theano to 0.9: error (theano.gpuarray): could not initialize pygpu, support disabled. I haven't try to reinstall everythin as you did in the end. I want to know if you make any change in the .theanorc file？ or only reinstall anaconda, mingw64 and theano?

**Comment by michaelklachko** [comment]
No I didn't change anything in theanorc aside from what has been discussed here. Honestly, reinstalling everything was not that hard to do, and in the end just using two conda commands to install Theano was pretty neat. You can also use separate environments, but that wouldn't work if you want to use Spyder.

**Comment by jingweimo** [comment]
@michaelklachko ：Thanks for you reply! I stick with using Spyder. I will do so later as you suggest

**Comment by jingweimo** [comment]
@michaelklachko：
Hello! I tried to install anaconda and theano as well its dependences, and unfortunately I still cannot succeed in importing theano with configuration for gpu. Without .theanorc file in the home directory, theano can be imported successfully, Otherwise, the importError will pop up:

       ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
       Traceback (most recent call last):
       File "C:\Users\YL\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 175, in <module>
    use(config.device)
       File "C:\Users\YL\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 162, in use
    init_dev(device, preallocate=preallocate)
       File "C:\Users\YL\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 65, in init_dev
    sched=config.gpuarray.sched)
      File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
      File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
      File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
      GpuArrayException: Error loading library: -1 

My .theanorc is rather simple:
       
       [cuda]
       root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

       [global]
       device = cuda
       floatX = float32
  
Do you know any possible reason for these?

**Comment by michaelklachko** [comment]
I don't, but here's my theanorc:
```

[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

[nvcc]
flags=-LC:\ProgramData\Miniconda2\libs
fastmath=True

[global]
device = cuda
floatX = float32
warn_float64=warn	
int_division=raise
print_active_device = True
optimizer_including = cudnn
allow_gc = False
assert_no_cpu_op=warn
warn.round=False

[lib]
cnmem = 0.4

[dnn]
enabled = True

include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
```

**Comment by abergeron** [comment]
Just a note to say that these sections don't do anything with the new backend:

```
[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

[nvcc]
flags=-LC:\ProgramData\Miniconda2\libs
fastmath=True

[lib]
cnmem = 0.4
```

The first two are simply not required anymore.  The last one should be replaced by

```
[gpuarray]
preallocate = 0.4
```

**Comment by michaelklachko** [comment]
@abergeron, thanks! I'm confused about fastmath: is it enabled by default now? How/where do I configure it?

**Comment by Iceman121** [comment]
Hello again,
I recently upgraded from Python 2.7 to 3.5 and reinstalled Theano. It works fine with `device = cpu`, but with `device = cuda`, I get the same errors as others above.

```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Continuum\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Continuum\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Continuum\lib\site-packages\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "C:\Continuum\lib\site-packages\theano\gpuarray\dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "C:\Continuum\lib\site-packages\theano\gpuarray\dnn.py", line 165, in dnn_present
    dnn_present.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'In file included from C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/driver_types.h:53:0,\r\n                 from C:\\Program Files\\NV
IDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/cudnn.h:63,\r\n                 from C:\\Users\\iceman\\AppData\\Local\\Temp\\try_flags_0filud1u.c:4:\r\nC:\\P
rogram Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/host_defines.h:84:0: warning: "__cdecl" redefined\r\n #define __cdecl\r\n ^\r\n<built-in>: note:
 this is the location of the previous definition\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64/cudnn.lib: error adding symbols: File
in wrong format\r\ncollect2.exe: error: ld returned 1 exit status\r\n'
```

Also, when I try the recommended theano config from above, I get a g++ error saying lazylinker.pyd and mod.cpp were not found.


Further, when I try to run the theano test script, both cpu and cuda modes work perfectly fine.

```
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x).transfer(None))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (numpy.asarray(r),))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```

My theanorc file is as below:
```
[global]
base_compiledir=/some/path
floatX = float32
device = cuda
optimizer = fast_run

[nvcc]
flags = -LC:\Python\Continuum\Anaconda2
compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
fastmath = True

[dnn]
enabled = True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

[lib]
cnmem = 0.8
```

Any thoughts?

**Comment by Iceman121** [comment]
Update: When I tried running the theano test script (with `device = cpu`) in command like, it gave me a DLL load error as follows:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    f = function([], tensor.exp(x))
  File "C:\Continuum\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Continuum\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Continuum\lib\site-packages\theano\compile\function_module.py", line 1795, in
    defaults)
  File "C:\Continuum\lib\site-packages\theano\compile\function_module.py", line 1661, in
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Continuum\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Continuum\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "C:\Continuum\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Continuum\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_
    module = lnk.compile_cmodule(location)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

But this script runs perfectly in Spyder.


With `device = cuda`, The error changes to:
```
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'In file included from C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/driver_types.h:53:0,\r\n                 from C:\\Program Files\\NV
IDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/cudnn.h:63,\r\n                 from C:\\Users\\iceman\\AppData\\Local\\Temp\\try_flags_0n69e_4z.c:4:\r\nC:\\P
rogram Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/host_defines.h:84:0: warning: "__cdecl" redefined\r\n #define __cdecl\r\n ^\r\n<built-in>: note:
 this is the location of the previous definition\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64/cudnn.lib: error adding symbols: File
in wrong format\r\ncollect2.exe: error: ld returned 1 exit status\r\n'
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    f = function([], tensor.exp(x))
  File "C:\Continuum\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Continuum\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Continuum\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Continuum\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Continuum\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Continuum\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "C:\Continuum\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Continuum\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Continuum\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "C:\Continuum\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

But again, runs perfectly in Spyder.

**Comment by notoraptor** [comment]
Hello ! Do you use the same Python environment in both Spyder and command line ? Also, which version of GCC do you use ? We recommend the version provided by conda package `m2w64-toolchain`: http://deeplearning.net/software/theano/install_windows.html#install-requirements-and-optional-packages .

**Comment by abergeron** [comment]
@michaelklachko fastmath is always disabled because we often had problem with wrong results due to the reduced precision.  In addition to that the NVIDIA docs don't recommend that it be enabled anymore.

**Comment by Iceman121** [comment]
@notoraptor Sorry for the late response. In Spyder I was using the iPython interpreter. The command line uses the default console python interpreter.

**Comment by notoraptor** [comment]
@Iceman121 What is the version of your console Python interpreter (result of command `python -V`), and what is the version of your Spyder's IPython ? Also, do you use a conda environment either in console or Spyder ?

**Comment by Iceman121** [comment]
@notoraptor 

Python version= 3.5.3
IPython = 6.0.0

Use of Conda environment= No.

**Comment by abergeron** [comment]
I just want to note that we only support conda packages on windows for pygpu/libgpuarray.

**Comment by notoraptor** [comment]
Hello, @Iceman121 . Sorry for late response, I was not working on Windows these las days.

But your problem is quite strange. Could you give the full output of following commands ?

In command line:
```batch
where python
python -V
gcc -v
conda info --envs
```

In Spyder IPython:
```python
import sys
print(sys.version)
print(sys.prefix)
```

The goal is to check if the Python interpreter in your command line is the same as the one in Spyder (do you have many Python installations in your system ?).

**Comment by Iceman121** [comment]
Hi @notoraptor 
Please find below-

In command line:
```
where python
C:\Continuum\python.exe

python -V
Python 3.5.3 :: Anaconda custom (64-bit)

gcc -v
Using built-in specs.
COLLECT_GCC=C:\Continuum\Scripts\gcc.bat\..\..\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/continuum/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/4.7.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../build/gcc/src/configure --target=x86_64-w64-mingw32 --prefix=/c/bb/vista64-mingw32/mingw-x86-x86_64/build/build/root --with-sysroot=/c
/bb/vista64-mingw32/mingw-x86-x86_64/build/build/root --enable-languages=all,obj-c++ --enable-fully-dynamic-string --disable-multilib
Thread model: win32
gcc version 4.7.0 20111220 (experimental) (GCC)

conda info --envs
# conda environments:
#
root                  *  C:\Continuum
```

For Spyder IPython:
```
print(sys.version)
3.5.3 |Anaconda custom (64-bit)| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)]

print(sys.prefix)
C:\Continuum
```

As far as I remember I have only one interpreter on my system. I think this validates it.

**Comment by notoraptor** [comment]
Hello, @Iceman121 , indeed, it seems there is only 1 Python installation. Quite strange that theano GPU test works in Spyder but not in console.

The last thing I could suggest is (in command line):
1. Check that you use `m2w64-toolchain` as gcc package (`conda install m2w64-toolchain`). If this package is installed, maybe you could find a `gcc` program in `C:\Continuum\Library\mingw-w64\bin\` ?
2. Make sure default conda environment (root) is activated (`activate root`).
3. Once `root` env is activated, then try theano test again. Also run `where gcc` to check if conda gcc package is indeed used in conda env.

**Comment by Iceman121** [comment]
@notoraptor Results below:
1. Found the gcc.exe in the Library location.
2. Done.
3. Tried, failed. `where gcc` responds as the same location.

**Comment by notoraptor** [comment]
Ok.

It seems I am encountering a similar problem as you, but with Python 3.5, not with Python 2.7.

Could you try to create a conda environment with Python 2.7 (e.g. `conda create -n python2 python=2`, then `activate python2`), install everything needed in that env ( http://www.deeplearning.net/software/theano_versions/dev/install_windows.html ) and check if theano GPU test works on command line with this environment ?

I'll check this issue for Python 3.5.

**Comment by ankushbbbr** [comment]
I have installed m2w64-toolchain and still getting the following error with libgpuarray.

Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'C:/Users/ankushbabbar/Miniconda2/envs/dlwin36/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudnn\r\ncollect2.exe: error: ld returned 1 exit status\r\n'

I'm using the follwing THEANO_FLAGS
THEANO_FLAGS=floatX=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=F:\Softwares\fast_ai\CUDA\v8.0\include,dnn.library_path=F:\Softwares\fast_ai\CUDA\v8.0\lib\x64

**Comment by abergeron** [comment]
The problem seems to be that you don't specify a bin_path for cudnn (which is important on windows).  

However, instead of specifying all the individual paths by hand try using the following flag instead of `dnn.include_path` and `dnn.library_path`: `cuda.root=F:\Softwares\fast_ai\CUDA\v8.0`  This should set all the other dnn flags automatically.
