### ISSUE TITLE
[Mac OS] AMD Fire Pro D500 Exception: 'compyte/array.h' file not found.

### ISSUE THREAD

**Issue by friskit-china** [Theano/libgpuarray#31]
After I installed Theano by pip, I ipython by environment of THEANO_FLAGS="floatX=float32,device=opencl0:0. It's ok to import theano. But when I compiled expresstion to a theano function, I got errors:

===============================
Problem occurred during compilation with the command line below:
g++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.10-intel.egg/pygpu -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -o /Users/shibotian/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.6-64/tmpMKZm7S/6009f7ce15109cbb7305d79e9f400e36.so /Users/shibotian/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.6-64/tmpMKZm7S/mod.cpp -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -lcompyte
/Users/shibotian/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.6-64/tmpMKZm7S/mod.cpp:6:10: fatal error: 'compyte/array.h' file not found
#include <compyte/array.h>
         ^
1 error generated.

Traceback (most recent call last):
  File "code/test.py", line 438, in <module>
    test()
  File "code/test.py", line 308, in test
    y: test_set_y[index * batch_size: (index + 1) * batch_size]
  File "/Library/Python/2.7/site-packages/theano/compile/function.py", line 223, in function
    profile=profile)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 512, in pfunc
    on_unused_input=on_unused_input)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1312, in orig_function
    defaults)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1181, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 434, in make_thunk
    output_storage=output_storage)[:3]
  File "/Library/Python/2.7/site-packages/theano/gof/vm.py", line 847, in make_all
    no_recycling))
  File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 606, in make_thunk
    output_storage=node_output_storage)
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 948, in make_thunk
    keep_lock=keep_lock)
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 891, in __compile__
    keep_lock=keep_lock)
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 1322, in cthunk_factory
    key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
  File "/Library/Python/2.7/site-packages/theano/gof/cmodule.py", line 996, in module_from_key
    module = next(compile_steps)
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 1237, in compile_cmodule_by_step
    preargs=preargs)
  File "/Library/Python/2.7/site-packages/theano/gof/cmodule.py", line 1971, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Shape_i{0}(<GpuArray<float32>>), '\n', "Compilation failed (return status=1): /Users/shibotian/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.6-64/tmpMKZm7S/mod.cpp:6:10: fatal error: 'compyte/array.h' file not found. #include <compyte/array.h>.          ^. 1 error generated.. ", '[Shape_i{0}(<GpuArray<float32>>)]')

What should I do??

Thank you

**Comment by abergeron** [comment]
The fix for the invalid value errors should be #36
