### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: Invalid value

### ISSUE THREAD

**Issue by pannous** [Theano/libgpuarray#34]
pygpu.init can't find Radeon GPU card:

>>> pygpu.init('opencl0:0').devname 
u'Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz' // CPU ok
>>> pygpu.init('opencl0:1').devname 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpuarray.pyx", line 587, in pygpu.gpuarray.init (pygpu/gpuarray.c:7113)
  File "gpuarray.pyx", line 558, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7051)
  File "gpuarray.pyx", line 962, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:10398)
pygpu.gpuarray.GpuArrayException: Invalid value

opencl0:1 is valid in pyopencl:
pyopencl.Device 'ATI Radeon HD 6970M' on 'Apple' at 0x1021b00

>>> pygpu.init('opencl0:2').devname
ValueError: No device 2  // OK, only 0 and 1 are valid devices

Is this card not supported or did something go wrong during installation/compilation?

**Comment by abergeron** [comment]
Can you try the master now?  It should be fixed, by working around AMD not following the standard.

**Comment by abergeron** [comment]
This should be fixed by #36
