### ISSUE TITLE
[pygpu] ERROR: Failure: GpuArrayException (Error loading library: -1)

### ISSUE THREAD

**Issue by mtomassoli** [Theano/libgpuarray#341]
I have the same problem as in issue #245 but the solutions there don't seem to work for my case.
I managed to build the dll with cmake and VS2013. I have 4 files:
```
gpuarray-static.lib
gpuarray.dll
gpuarray.exp
gpuarray.lib
```
I tried copying them to windows, windows\system32 and adding a path for them. In fact, `where gpuarray.dll` works correctly.

I installed pygpu without any errors and the pyd files are present.

If I try to import pygpu and pygpu.gpuarray I get no message, but when I execute pygpu.test() I get many "ERROR: Failure: GpuArrayException (Error loading library: -1)"

Here's the first error in detail:

```
>>> pygpu.test()
pygpu is installed in C:\Users\Kiuhnm\Anaconda3\lib\site-packages\pygpu-0.6.0-py3.5-win-amd64.egg\pygpu
NumPy version 1.11.2
NumPy relaxed strides checking option: False
NumPy is installed in C:\Users\Kiuhnm\Anaconda3\lib\site-packages\numpy
Python version 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
EEEEEE
======================================================================
ERROR: Failure: GpuArrayException (Error loading library: -1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\Kiuhnm\Anaconda3\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Users\Kiuhnm\Anaconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\pygpu-0.6.0-py3.5-win-amd64.egg\pygpu\tests\test_blas.py", line 5, in <module>
    from .support import (guard_devsup, gen_gpuarray, context)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\pygpu-0.6.0-py3.5-win-amd64.egg\pygpu\tests\support.py", line 32, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9220)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8911)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13273)
pygpu.gpuarray.GpuArrayException: Error loading library: -1

```

**Comment by mtomassoli** [comment]
That's odd because everything worked fine before I tried to switch to the new backend. Here's what I get if I execute `nvcc --version`:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:49:10_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by abergeron** [comment]
The old backend invokes nvcc to build cuda code.  The new one dynamically loads the libraries.  Since they aren't doing the same thing, it's normal that there might be some behaviour discrepancies.

To confirm which library it has a problem with you can try a debug build which should print the name of the library that failed to load.

**Comment by mtomassoli** [comment]
Do you mean a debug build of gpuarray? The error message is the same.
I launched procmon and I found out that python is looking for `C:\Windows\System32\pygpu\gpuarray.pyx` and `nvrtc64_80.dll`. Do I need CUDA 8.0? And what's gpuarray.pyx?

**Comment by abergeron** [comment]
Ok this means that you have the driver for cuda8 so gpuarray tries to load the rest of the libraries that go with it.

If you want to use cuda 7.5 export `GPUARRAY_CUDA_VERSION=75`

**Comment by mtomassoli** [comment]
I updated cuda and now pygpu works fine. Now I get a compilation error in Theano ("Optimization failure due to: constant_folding") but this is an unrelated issue, right?

**Comment by nouiz** [comment]
For the new error, make an issue in Theano.
