### ISSUE TITLE
fatal error: gpuarray/array.h: No such file or directory

### ISSUE THREAD

**Issue by mtomassoli** [Theano/libgpuarray#343]
I'm using `device = cuda` in .theanorc.

Here's a minimal code to reproduce the error:

```
import theano.tensor as T

X = T.tensor3('X')
# f = theano.function([X], X)         # OK
f = theano.function([X], abs(X))    # Error!
```

And here's the full error:

```
Mapped name None to device cuda: GeForce GTX 970
PCI Bus ID: 0000:01:00.0
===============================
00001	#include <Python.h>
00002	#include <iostream>
00003	#include "theano_mod_helper.h"
00004	#include <gpuarray/array.h>
00005	#include <gpuarray/kernel.h>
00006	#include <gpuarray/error.h>
00007	#include <gpuarray/buffer.h>
00008	#include <gpuarray/buffer_blas.h>
00009	#include <numpy/arrayobject.h>
00010	#include <gpuarray_api.h>
00011	#include <math.h>
00012	#include <numpy/arrayscalars.h>
00013	#include "gpuarray_helper.h"
00014	//////////////////////
00015	////  Support Code
00016	//////////////////////
00017	
00018	    namespace {
00019	    struct __struct_compiled_op_m297761dc268d328d781f966722d6523c {
00020	        PyObject* __ERROR;
00021	
00022	        PyObject* storage_V3;
00023	PyObject* storage_V1;
00024	PyObject* storage_V5;
00025	        
00026	    PyObject* py_V5;
00027	    PyGpuContextObject *V5;
00028	
00029	        __struct_compiled_op_m297761dc268d328d781f966722d6523c() {
00030	            // This is only somewhat safe because we:
00031	            //  1) Are not a virtual class
00032	            //  2) Do not use any virtual classes in the members
00033	            //  3) Deal with mostly POD and pointers
00034	
00035	            // If this changes, we would have to revise this, but for
00036	            // now I am tired of chasing segfaults because
00037	            // initialization code had an error and some pointer has
00038	            // a junk value.
00039	            memset(this, 0, sizeof(*this));
00040	        }
00041	        ~__struct_compiled_op_m297761dc268d328d781f966722d6523c(void) {
00042	            cleanup();
00043	        }
00044	
00045	        int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1, PyObject* storage_V5) {
00046	            Py_XINCREF(storage_V3);
00047	Py_XINCREF(storage_V1);
00048	Py_XINCREF(storage_V5);
00049	            this->storage_V3 = storage_V3;
00050	this->storage_V1 = storage_V1;
00051	this->storage_V5 = storage_V5;
00052	            
00053	
00054	
00055	
00056	    py_V5 = PyList_GET_ITEM(storage_V5, 0);
00057	    {Py_XINCREF(py_V5);}
00058	    
00059	if (!PyObject_TypeCheck(py_V5, &PyGpuContextType)) {
00060	  PyErr_SetString(PyExc_TypeError, "expected a GpuContext");
00061	  {
00062	        if (!PyErr_Occurred()) {
00063	            PyErr_SetString(PyExc_RuntimeError,
00064	                "Unexpected error in an Op's C code. "
00065	                "No Python exception was set.");
00066	            }
00067	        return 5;
00068	}
00069	}
00070	
00071	V5 = (PyGpuContextObject *)py_V5;
00072	Py_INCREF(V5);
00073	
00074	
00075	            this->__ERROR = __ERROR;
00076	            return 0;
00077	        }
00078	        void cleanup(void) {
00079	            __label_1:
00080	
00081	double __DUMMY_1;
00082	__label_3:
00083	
00084	double __DUMMY_3;
00085	__label_5:
00086	Py_XDECREF(V5); V5 = NULL;
00087	    {Py_XDECREF(py_V5);}
00088	    
00089	double __DUMMY_5;
00090	__label_8:
00091	
00092	double __DUMMY_8;
00093	
00094	            Py_XDECREF(this->storage_V3);
00095	Py_XDECREF(this->storage_V1);
00096	Py_XDECREF(this->storage_V5);
00097	        }
00098	        int run(void) {
00099	            int __failure = 0;
00100	            
00101	    PyObject* py_V1;
00102	    
00103	        PyGpuArrayObject *V1;
00104	        
00105	    PyObject* py_V3;
00106	    
00107	        PyArrayObject* V3;
00108	        
00109	            typedef npy_float32 dtype_V3;
00110	            
00111	{
00112	
00113	    py_V1 = PyList_GET_ITEM(storage_V1, 0);
00114	    {Py_XINCREF(py_V1);}
00115	    
00116	        if (py_V1 == Py_None)
00117	        {
00118	            V1 = NULL;
00119	        }
00120	        else
00121	        {
00122	            
00123	        V1 = NULL;
00124	        if (py_V1 == Py_None) {
00125	            PyErr_SetString(PyExc_ValueError, "expected a GpuArray, not None");
00126	            {
00127	        __failure = 2;
00128	        if (!PyErr_Occurred()) {
00129	            PyErr_SetString(PyExc_RuntimeError,
00130	                "Unexpected error in an Op's C code. "
00131	                "No Python exception was set.");
00132	            }
00133	        goto __label_2;}
00134	        }
00135	        /* First check if we are the base type exactly (the most common case),
00136	           then do the full subclass check if needed. */
00137	        if (py_V1->ob_type != &PyGpuArrayType &&
00138	            !PyObject_TypeCheck(py_V1, &PyGpuArrayType)) {
00139	            PyErr_SetString(PyExc_ValueError, "expected a GpuArray");
00140	            {
00141	        __failure = 2;
00142	        if (!PyErr_Occurred()) {
00143	            PyErr_SetString(PyExc_RuntimeError,
00144	                "Unexpected error in an Op's C code. "
00145	                "No Python exception was set.");
00146	            }
00147	        goto __label_2;}
00148	        }
00149	        V1 = (PyGpuArrayObject *)py_V1;
00150	        Py_INCREF(V1);
00151	        
00152	        }
00153	        
00154	{
00155	
00156	    py_V3 = PyList_GET_ITEM(storage_V3, 0);
00157	    {Py_XINCREF(py_V3);}
00158	    
00159	            V3 = NULL;
00160	            if (py_V3 == Py_None) {
00161	                // We can either fail here or set V3 to NULL and rely on Ops
00162	                // using tensors to handle the NULL case, but if they fail to do so
00163	                // they'll end up with nasty segfaults, so this is public service.
00164	                PyErr_SetString(PyExc_ValueError, "expected an ndarray, not None");
00165	                {
00166	        __failure = 4;
00167	        if (!PyErr_Occurred()) {
00168	            PyErr_SetString(PyExc_RuntimeError,
00169	                "Unexpected error in an Op's C code. "
00170	                "No Python exception was set.");
00171	            }
00172	        goto __label_4;}
00173	            }
00174	            if (!PyArray_Check(py_V3)) {
00175	                PyErr_SetString(PyExc_ValueError, "expected an ndarray");
00176	                {
00177	        __failure = 4;
00178	        if (!PyErr_Occurred()) {
00179	            PyErr_SetString(PyExc_RuntimeError,
00180	                "Unexpected error in an Op's C code. "
00181	                "No Python exception was set.");
00182	            }
00183	        goto __label_4;}
00184	            }
00185	            // We expect NPY_FLOAT32
00186	            if (!PyArray_ISALIGNED((PyArrayObject*) py_V3)) {
00187	                PyArrayObject * tmp = (PyArrayObject*) py_V3;
00188	                PyErr_Format(PyExc_NotImplementedError,
00189	                             "expected an aligned array of type %ld "
00190	                             "(NPY_FLOAT32), got non-aligned array of type %ld"
00191	                             " with %ld dimensions, with 3 last dims "
00192	                             "%ld, %ld, %ld"
00193	                             " and 3 last strides %ld %ld, %ld.",
00194	                             (long int) NPY_FLOAT32,
00195	                             (long int) PyArray_TYPE((PyArrayObject*) py_V3),
00196	                             (long int) PyArray_NDIM(tmp),
00197	                             (long int) (PyArray_NDIM(tmp) >= 3 ?
00198	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-3] : -1),
00199	                             (long int) (PyArray_NDIM(tmp) >= 2 ?
00200	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-2] : -1),
00201	                             (long int) (PyArray_NDIM(tmp) >= 1 ?
00202	            PyArray_DIMS(tmp)[PyArray_NDIM(tmp)-1] : -1),
00203	                             (long int) (PyArray_NDIM(tmp) >= 3 ?
00204	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-3] : -1),
00205	                             (long int) (PyArray_NDIM(tmp) >= 2 ?
00206	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-2] : -1),
00207	                             (long int) (PyArray_NDIM(tmp) >= 1 ?
00208	            PyArray_STRIDES(tmp)[PyArray_NDIM(tmp)-1] : -1)
00209	            );
00210	                {
00211	        __failure = 4;
00212	        if (!PyErr_Occurred()) {
00213	            PyErr_SetString(PyExc_RuntimeError,
00214	                "Unexpected error in an Op's C code. "
00215	                "No Python exception was set.");
00216	            }
00217	        goto __label_4;}
00218	            }
00219	            // This is a TypeError to be consistent with DEBUG_MODE
00220	            // Note: DEBUG_MODE also tells the name of the container
00221	            if (PyArray_TYPE((PyArrayObject*) py_V3) != NPY_FLOAT32) {
00222	                PyErr_Format(PyExc_TypeError,
00223	                             "expected type_num %d (NPY_FLOAT32) got %d",
00224	                             NPY_FLOAT32, PyArray_TYPE((PyArrayObject*) py_V3));
00225	                {
00226	        __failure = 4;
00227	        if (!PyErr_Occurred()) {
00228	            PyErr_SetString(PyExc_RuntimeError,
00229	                "Unexpected error in an Op's C code. "
00230	                "No Python exception was set.");
00231	            }
00232	        goto __label_4;}
00233	            }
00234	            
00235	        V3 = (PyArrayObject*)(py_V3);
00236	        Py_XINCREF(V3);
00237	        
00238	{
00239	
00240	{
00241	// Op class GpuFromHost
00242	
00243	        PyArrayObject *node_m297761dc268d328d781f966722d6523c_0_tmp;
00244	        node_m297761dc268d328d781f966722d6523c_0_tmp = PyArray_GETCONTIGUOUS(V3);
00245	        int err;
00246	        if (node_m297761dc268d328d781f966722d6523c_0_tmp == NULL)
00247	          {
00248	        __failure = 7;
00249	        if (!PyErr_Occurred()) {
00250	            PyErr_SetString(PyExc_RuntimeError,
00251	                "Unexpected error in an Op's C code. "
00252	                "No Python exception was set.");
00253	            }
00254	        goto __label_7;}
00255	
00256	        if (V1 != NULL && GpuArray_IS_C_CONTIGUOUS(&V1->ga) &&
00257	            theano_size_check(V1, PyArray_NDIM(node_m297761dc268d328d781f966722d6523c_0_tmp),
00258	                              (size_t *)PyArray_DIMS(node_m297761dc268d328d781f966722d6523c_0_tmp),
00259	                              get_typecode((PyObject *)PyArray_DESCR(node_m297761dc268d328d781f966722d6523c_0_tmp)))) {
00260	          Py_BEGIN_ALLOW_THREADS
00261	          err = GpuArray_write(&V1->ga, PyArray_DATA(node_m297761dc268d328d781f966722d6523c_0_tmp),
00262	                               PyArray_NBYTES(node_m297761dc268d328d781f966722d6523c_0_tmp));
00263	          Py_END_ALLOW_THREADS
00264	          Py_DECREF(node_m297761dc268d328d781f966722d6523c_0_tmp);
00265	          if (err != GA_NO_ERROR) {
00266	            PyErr_Format(PyExc_RuntimeError, "Could not write data to gpu");
00267	            {
00268	        __failure = 7;
00269	        if (!PyErr_Occurred()) {
00270	            PyErr_SetString(PyExc_RuntimeError,
00271	                "Unexpected error in an Op's C code. "
00272	                "No Python exception was set.");
00273	            }
00274	        goto __label_7;};
00275	          }
00276	        } else {
00277	          Py_XDECREF(V1);
00278	          // This method will release the GIL when needed.
00279	          V1 = pygpu_fromhostdata(PyArray_DATA(node_m297761dc268d328d781f966722d6523c_0_tmp),
00280	                                       get_typecode((PyObject *)PyArray_DESCR(node_m297761dc268d328d781f966722d6523c_0_tmp)),
00281	                                       PyArray_NDIM(node_m297761dc268d328d781f966722d6523c_0_tmp),
00282	                                       (size_t *)PyArray_DIMS(node_m297761dc268d328d781f966722d6523c_0_tmp),
00283	                                       (ssize_t *)PyArray_STRIDES(node_m297761dc268d328d781f966722d6523c_0_tmp),
00284	                                       V5,
00285	                                       Py_None);
00286	          Py_DECREF(node_m297761dc268d328d781f966722d6523c_0_tmp);
00287	          if (V1 == NULL) {
00288	              {
00289	        __failure = 7;
00290	        if (!PyErr_Occurred()) {
00291	            PyErr_SetString(PyExc_RuntimeError,
00292	                "Unexpected error in an Op's C code. "
00293	                "No Python exception was set.");
00294	            }
00295	        goto __label_7;}
00296	          }
00297	        }
00298	        __label_7:
00299	
00300	double __DUMMY_7;
00301	
00302	}
00303	__label_6:
00304	
00305	double __DUMMY_6;
00306	
00307	}
00308	__label_4:
00309	
00310	        if (V3) {
00311	            Py_XDECREF(V3);
00312	        }
00313	        
00314	    {Py_XDECREF(py_V3);}
00315	    
00316	double __DUMMY_4;
00317	
00318	}
00319	__label_2:
00320	
00321	    if (!__failure) {
00322	      
00323	        if (!V1) {
00324	            Py_XDECREF(py_V1);
00325	            Py_INCREF(Py_None);
00326	            py_V1 = Py_None;
00327	        } else if ((void *)py_V1 != (void *)V1) {
00328	            Py_XDECREF(py_V1);
00329	            py_V1 = (PyObject *)V1;
00330	            Py_INCREF(py_V1);
00331	        }
00332	        
00333	      PyObject* old = PyList_GET_ITEM(storage_V1, 0);
00334	      {Py_XINCREF(py_V1);}
00335	      PyList_SET_ITEM(storage_V1, 0, py_V1);
00336	      {Py_XDECREF(old);}
00337	    }
00338	    Py_XDECREF(V1); V1 = NULL;
00339	    {Py_XDECREF(py_V1);}
00340	    
00341	double __DUMMY_2;
00342	
00343	}
00344	
00345	            
00346	        if (__failure) {
00347	            // When there is a failure, this code puts the exception
00348	            // in __ERROR.
00349	            PyObject* err_type = NULL;
00350	            PyObject* err_msg = NULL;
00351	            PyObject* err_traceback = NULL;
00352	            PyErr_Fetch(&err_type, &err_msg, &err_traceback);
00353	            if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
00354	            if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
00355	            if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
00356	            PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
00357	            PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
00358	            PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
00359	            PyList_SET_ITEM(__ERROR, 0, err_type);
00360	            PyList_SET_ITEM(__ERROR, 1, err_msg);
00361	            PyList_SET_ITEM(__ERROR, 2, err_traceback);
00362	            {Py_XDECREF(old_err_type);}
00363	            {Py_XDECREF(old_err_msg);}
00364	            {Py_XDECREF(old_err_traceback);}
00365	        }
00366	        // The failure code is returned to index what code block failed.
00367	        return __failure;
00368	        
00369	        }
00370	    };
00371	    }
00372	    
00373	
00374	        static int __struct_compiled_op_m297761dc268d328d781f966722d6523c_executor(__struct_compiled_op_m297761dc268d328d781f966722d6523c *self) {
00375	            return self->run();
00376	        }
00377	
00378	        static void __struct_compiled_op_m297761dc268d328d781f966722d6523c_destructor(PyObject *capsule) {
00379	            __struct_compiled_op_m297761dc268d328d781f966722d6523c *self = (__struct_compiled_op_m297761dc268d328d781f966722d6523c *)PyCapsule_GetContext(capsule);
00380	            delete self;
00381	        }
00382	        
00383	//////////////////////
00384	////  Functions
00385	//////////////////////
00386	static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
00387	  assert(PyTuple_Check(argtuple));
00388	  if (4 != PyTuple_Size(argtuple)){ 
00389	     PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 4, got %i", (int)PyTuple_Size(argtuple));
00390	     return NULL;
00391	  }
00392	  __struct_compiled_op_m297761dc268d328d781f966722d6523c* struct_ptr = new __struct_compiled_op_m297761dc268d328d781f966722d6523c();
00393	  if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2),PyTuple_GET_ITEM(argtuple, 3) ) != 0) {
00394	    delete struct_ptr;
00395	    return NULL;
00396	  }
00397	    PyObject* thunk = PyCapsule_New((void*)(&__struct_compiled_op_m297761dc268d328d781f966722d6523c_executor), NULL, __struct_compiled_op_m297761dc268d328d781f966722d6523c_destructor);
00398	    if (thunk != NULL && PyCapsule_SetContext(thunk, struct_ptr) != 0) {
00399	        PyErr_Clear();
00400	        Py_DECREF(thunk);
00401	        thunk = NULL;
00402	    }
00403	
00404	  return thunk; }
00405	
00406	//////////////////////
00407	////  Module init
00408	//////////////////////
00409	static PyMethodDef MyMethods[] = {
00410		{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
00411		{NULL, NULL, 0, NULL}
00412	};
00413	static struct PyModuleDef moduledef = {
00414	      PyModuleDef_HEAD_INIT,
00415	      "m297761dc268d328d781f966722d6523c",
00416	      NULL,
00417	      -1,
00418	      MyMethods,
00419	};
00420	
00421	PyMODINIT_FUNC PyInit_m297761dc268d328d781f966722d6523c(void) {
00422	   import_pygpu__gpuarray();
00423	   import_array();
00424	    PyObject *m = PyModule_Create(&moduledef);
00425	    return m;
00426	}
00427	
===============================
Problem occurred during compilation with the command line below:
C:\Users\Kiuhnm\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\tmpql0azk2b\mod.cpp:4:28: fatal error: gpuarray/array.h: No such file or directory
compilation terminated.

"C:\mingw64\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Users\Kiuhnm\Anaconda3\lib\site-packages\pygpu-0.6.0-py3.5-win-amd64.egg\pygpu" -I"C:\Users\Kiuhnm\Anaconda3\lib\site-packages\numpy\core\include" -I"C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gpuarray" -I"C:\Users\Kiuhnm\Anaconda3\lib\site-packages\numpy\core\include" -I"C:\Users\Kiuhnm\Anaconda3\include" -I"C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof" -L"C:\Users\Kiuhnm\Anaconda3\libs" -L"C:\Users\Kiuhnm\Anaconda3" -o C:\Users\Kiuhnm\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\tmpql0azk2b\m297761dc268d328d781f966722d6523c.pyd C:\Users\Kiuhnm\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\tmpql0azk2b\mod.cpp -lgpuarray -lpython35
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/--- New Projects/Theano/SDL/test_error.py", line 8, in <module>
    f = theano.function([X], abs(X))    # Error!
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\compile\function_module.py", line 1784, in orig_function
    defaults)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\compile\function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\vm.py", line 1059, in make_all
    impl=impl))
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "C:\Users\Kiuhnm\Anaconda3\lib\site-packages\theano\theano\gof\cmodule.py", line 2323, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', GpuFromHost<None>(X), '\n', 'Compilation failed (return status=1): C:\\Users\\Kiuhnm\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\\tmpql0azk2b\\mod.cpp:4:28: fatal error: gpuarray/array.h: No such file or directory\r. compilation terminated.\r. ', '[GpuFromHost<None>(X)]')

Process finished with exit code 1
```

**Comment by nouiz** [comment]
There is a PR that try to fix this:

https://github.com/Theano/Theano/pull/5479

Can you try it and tell if it work for you?

**Comment by mtomassoli** [comment]
I tried to apply the fix and so I found out that a develop install of Theano 0.8 was hiding the new installation of Theano 0.9.
Also, I installed libgpuarray manually so I don't need the fix. I didn't copied the include files in anaconda3/include because I don't know the Python ecosystem well.
Now I have another problem: Theano tries to use mingw installed in c:\mingw64 but it doesn't work. How can I tell Theano to use VS2013 instead?

**Comment by abergeron** [comment]
You shouldn't have to copy any files around.  That fix is if you use the conda package for libgpuarray.

As for the second problem, Theano can't use Visual Studio at all. You need a version of gcc.  You can install the m2w64-toolchain package with conda to get one that works.

**Comment by mtomassoli** [comment]
As for the files, I had array.h, etc... in Anaconda3\Lib\site-packages\libgpuarray\src\gpuarray and I had to copy the directory gpuarray in Anaconda3\include.
I used the instruction in http://deeplearning.net/software/libgpuarray/installation.html to install libgpuarray. gpuarray was working, but theano couldn't find gpuarray/array.h.

**Comment by mtomassoli** [comment]
Now when I import theano I get an error because mingw64 is looking for cuda includes in the wrong places:

```
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Lib\site-packages\Theano\theano\gpuarray\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\lib\gcc\x86_64-w64-mingw32\5.3.0\include\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\include\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\lib\gcc\x86_64-w64-mingw32\5.3.0\include-fixed\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\x86_64-w64-mingw32\include\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\include\c++\5.3.0\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\include\c++\5.3.0\x86_64-w64-mingw32\cudnn.h	
cc1plus.exe	C:\Users\Kiuhnm\Anaconda3\Library\mingw-w64\include\c++\5.3.0\backward\cudnn.h	
```

If I copy cudnn.h to C:\Users\Kiuhnm\Anaconda3\Lib\site-packages\Theano\theano\gpuarray\ then it works, but I don't like copying all the includes.

Is there a way to add an include directory to mingw? I installed m2w64-toolchain through conda. Either Windows is not well supported or I'm being a little unlucky :(

**Comment by nouiz** [comment]
We merged today a PR in Theano that help find gpuarray headers. Can you test if it fix problems for you?

You can use that theano flags to add extra compiler argument: gcc.cxxflags="-LPATH -IPATH"

**Comment by mtomassoli** [comment]
I fixed all my problems 2 days ago by moving the right files to Anaconda3\Library\mingw-w64\include and \lib. I prefer not to touch anything anymore.

**Comment by mtomassoli** [comment]
I tried those flags but there's a problem.

Without flags the compiler told me it couldn't find gpuarray/array.h, so I added

    [gcc]
    cxxflags="-IC:\Users\Kiuhnm\Anaconda3\Lib\site-packages\libgpuarray\src"

in .theanorc. (Note that it doesn't work with a final '\').
Then it complained that it couldn't find the lib gpuarray so I added -L:

    [gcc]
    cxxflags="-IC:\Users\Kiuhnm\Anaconda3\Lib\site-packages\libgpuarray\src -LC:\Users\Kiuhnm\Anaconda3\Lib\site-packages\libgpuarray\lib\Release"

Now it can't find gpuarray/array.h anymore :(

**Comment by abergeron** [comment]
Remove the cxxflags, update Theano and try again.

**Comment by mtomassoli** [comment]
There's nothing to update according to git.

**Comment by abergeron** [comment]
Scratch what I've said.  You never installed libgpuarray so the headers and libraries are just laying there in the source.

Try using the conda pacakges: `conda install -c rdonnelly pygpu`.

**Comment by mtomassoli** [comment]
OK, it works, but there's still the problem with the cxxflags regarding cudnn.

As before, specifying a path with -I works, but when I add -L it doesn't work anymore.
I'm using this:

```
[gcc]
cxxflags="-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include -LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64"

```

**Comment by abergeron** [comment]
Theano doesn't properly quote path with spaces on windows if I recall, so using 8.3 paths should work.

Also, this question no longer has anything to do with libgpuarray.  You should post a ticket on Theano or ask on theano-users.

**Comment by mtomassoli** [comment]
OK, anyway it doesn't work. It's not a problem with 8.3 paths. In fact, if you remember, it didn't work even before with

```
[gcc]
cxxflags="-IC:\Users\Kiuhnm\Anaconda3\Lib\site-packages\libgpuarray\src -LC:\Users\Kiuhnm\Anaconda3\Lib\site-packages\libgpuarray\lib\Release"
```

**Comment by stevenxxiu** [comment]
The following didn't error for me, however theano crashed instantly:


    [gcc]
    cxxflags="-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" "-LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64"

**Comment by nouiz** [comment]
Do you have an error? Can you give the full error?
