### ISSUE TITLE
Support indexing with None for new axes

### ISSUE THREAD

**Issue by kohr-h** [Theano/libgpuarray#365]
It would be nice to be able to index arrays like `x[:, None]` to create new artificial axes, since broadcasting is already supported:
```python
>>> x = pygpu.gpuarray.array([1, 2, 3], cls=pygpu.ndgpuarray)
>>> x.reshape((3, 1)) + x.reshape((1, 3))
gpuarray.array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```
But the indexing gives an error:
```python
>>> x[:, None]
Traceback (most recent call last):

  File "<ipython-input-14-9b3b3d2c380e>", line 1, in <module>
    x[:, None]

  File "pygpu/gpuarray.pyx", line 1839, in pygpu.gpuarray.GpuArray.__getitem__ (pygpu/gpuarray.c:23530)

  File "pygpu/gpuarray.pyx", line 1884, in pygpu.gpuarray.GpuArray.__cgetitem__ (pygpu/gpuarray.c:24063)

IndexError: too many indices
```
Are there any big headaches with this type of addition to `__getitem__`?

**Comment by abergeron** [comment]
There are no big headaches that I know of, we just need someone to do it.
