### ISSUE TITLE
ImportError: cannot import name 'gpuarray'

### ISSUE THREAD

**Issue by josemonteiro** [Theano/libgpuarray#367]
I'm trying to install libgpuarray locally (in `~/.local/`) and the python bindings in a virtual environment (`new-gpu-backend`).

I followed these instructions:
```
git clone https://github.com/Theano/libgpuarray.git
cd libgpuarray

mkdir Build
cd Build
cmake .. -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release
make
make install

export CPATH=$CPATH:~/.local/include
export LIBRARY_PATH=$LIBRARY_PATH:~/.local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.local/lib
# added the above 3 lines to ~/.bashrc

cd ..
mkvirtualenv new-gpu-backend
pip install Cython nose numpy
python setup.py build_ext -L ~/.local/lib -I ~/.local/include
python setup.py install
```

When running the tests (inside the virtual environment), I get this result:
```
$ python -c "import pygpu;pygpu.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu/elemwise.py", line 3, in <module>
    from .dtypes import dtype_to_ctype, get_common_dtype
  File "pygpu/dtypes.py", line 6, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray
```

I'm running this on Ubuntu . Am I doing something wrong?

**Comment by nouiz** [comment]
Try to run the tests outside the directory libgpuarray directory. If that
don't work, how do you run the tests?

I think it import the current directory, not the pygpu installed version.

**Comment by josemonteiro** [comment]
Perfect, that was it! Thanks!
