### ISSUE TITLE
Several errors importing theano on the new backend

### ISSUE THREAD

**Issue by Dapid** [Theano/libgpuarray#372]
I am not able to run on the new backend. Using [this file](https://raw.githubusercontent.com/fchollet/keras/master/examples/mnist_cnn.py), I can run it successfully setting device=gpu

```
Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1070 (CNMeM is enabled with initial size: 40 MB, cuDNN 5105)
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 2s - loss: 0.3817 - acc: 0.8827 - val_loss: 0.1015 - val_acc: 0.9687
```

Note that it finds cuDNN. But switching to the new backend, it fails with several errors:

```
$ python mnist_cnn.py 
Using Theano backend.
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 68, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gpuarray/dnn.py", line 80, in _make_handle
    cudnn = _dnn_lib()
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gpuarray/dnn.py", line 67, in _dnn_lib
    raise RuntimeError('Could not find cudnn library (looked for v5[.1])')
RuntimeError: Could not find cudnn library (looked for v5[.1])
```
Despite this error, the program continues:

```
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 942, in compile_args
    ret += x.c_compile_args(c_compiler)
TypeError: c_compile_args() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/tensor/blas.py", line 441, in _ldflags
    assert t0 == '-'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 79, in <module>
    verbose=1, validation_data=(X_test, Y_test))
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 1137, in fit
    self._make_test_function()
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 782, in _make_test_function
    **self._function_kwargs)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/vm.py", line 1047, in make_all
    impl=impl))
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 1575, in cthunk_factory
    key = self.cmodule_key()
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 1268, in cmodule_key
    compile_args=self.compile_args(),
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/cc.py", line 944, in compile_args
    ret += x.c_compile_args()
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/tensor/nnet/corr.py", line 109, in c_compile_args
    compile_args = ldflags(libs=False, flags=True)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/tensor/blas.py", line 386, in ldflags
    include_dir=include_dir)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/gof/utils.py", line 257, in rval
    val = f(*args, **kwargs)
  File "/home/david/.virtualenvs/py35/lib/python3.5/site-packages/theano/tensor/blas.py", line 444, in _ldflags
    % (t, ldflags_str))
ValueError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1)}(convolution2d_input_1, Subtensor{::, ::, ::int64, ::int64}.0), '\n', 'invalid token ""-L/usr/lib64/libopenblasp.so" in ldflags_str: ""-L/usr/lib64/libopenblasp.so -lopenblas""')
```

Running `pygpu.__version__ ` gives `'0.6.2'`. I am running theano 0.9.0rc3 installed from pypi on Linux.

**Comment by Dapid** [comment]
The problem was on my setup. For some reason, ldconfig stopped picking up cudnn, now fixed.

**Comment by shihuaxing** [comment]
I met the same error. how you fix that??

**Comment by Dapid** [comment]
I think that I put `/usr/local/cuda/lib64` (my cuda path) in `/etc/ld.so.conf.d/cuda.conf` and reload ldconfig.

**Comment by DanielTakeshi** [comment]
@Dapid What were the exact lines you copied into the `cuda.conf` file? I'm getting this same error.

**Comment by abergeron** [comment]
The official cuda package does that for you.  If you need to do it manually you are probably using a distribution's package which most of the time breaks something for compute.

Please use official packages.

Also, if you have a problem with the usage of libgpuarray with Theano please post a question on stackexchange or in the theano-users mailing list.
