### ISSUE TITLE
Compilation error in new backend on Win10

### ISSUE THREAD

**Issue by 3qty** [Theano/libgpuarray#377]
Hi 
I install the libgpuarray and pygpu using command "conda install -c rdonnelly pygpu" and can import pygpu successfully. But when I run the test following the instruction:

```
import numpy as np
import time
import theano
A = np.random.rand(1000,10000).astype(theano.config.floatX)
B = np.random.rand(10000,1000).astype(theano.config.floatX)
np_start = time.time()
AB = A.dot(B)
np_end = time.time()
X,Y = theano.tensor.matrices('XY')
mf = theano.function([X,Y],X.dot(Y))
t_start = time.time()
tAB = mf(A,B)
t_end = time.time()
print("NP time: %f[s], theano time: %f[s] (times should be close when run on CPU!)" %(
                                           np_end-np_start, t_end-t_start))
print("Result difference: %f" % (np.abs(AB-tAB).max(), ))
```

I get the following error

```
Problem occurred during compilation with the command line below:
"E:\TDM-GCC-64\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"E:\Anaconda2\lib\site-packages\pygpu" -I"E:\Anaconda2\lib\site-packages\numpy\core\include" -I"E:\Anaconda2\Library\include" -I"E:\Anaconda2\include" -I"E:\Anaconda2\lib\site-packages\theano\gpuarray" -I"E:\Anaconda2\lib\site-packages\numpy\core\include" -I"E:\Anaconda2\include" -I"E:\Anaconda2\lib\site-packages\theano\gof" -L"E:\Anaconda2\Library\lib" -L"E:\Anaconda2\lib" -L"E:\Anaconda2\libs" -L"E:\Anaconda2" -o C:\Users\Hasee\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.13-64\tmpfjaxl_\1796c15cab36ad584c635b2d27dfd758.pyd C:\Users\Hasee\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.13-64\tmpfjaxl_\mod.cpp -lgpuarray -lpython27
E:\Anaconda2\Library\lib/gpuarray.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    mf = theano.function([X,Y],X.dot(Y))
  File "E:\Anaconda2\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "E:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "E:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "E:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "E:\Anaconda2\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "E:\Anaconda2\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "E:\Anaconda2\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "E:\Anaconda2\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "E:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2304, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', GpuFromHost<None>(Y), '\n', 'Compilation failed (return status=1): E:\\Anaconda2\\Library\\lib/gpuarray.lib: error adding symbols: File in wrong format\r. collect2.exe: error: ld returned 1 exit status\r. ', '[GpuFromHost<None>(Y)]')

```

I can run the test in old backend

**Comment by abergeron** [comment]
You probably mixed 32/64 bits.  To avoid that make sure to use the gcc from Anaconda, not an external install.

**Comment by 3qty** [comment]
Thanks! I have solved it using internal gcc.
