### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by cdg720** [Theano/libgpuarray#38]
Hi, 

I get the following errors when I run "python -c "import pygpu;pygpu.test()"".

315 GpuArrayExceptions. The below is an example.
======================================================================
ERROR: pygpu.tests.test_blas.test_gemv((100, 128), 'float32', 'f', False, True, 1, True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dokookchoe/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/tests/test_blas.py", line 61, in gemv
    overwrite_y=overwrite)
  File "pygpu/blas.pyx", line 72, in pygpu.blas.gemv (pygpu/blas.c:1981)
  File "pygpu/blas.pyx", line 27, in pygpu.blas.pygpu_blas_rgemv (pygpu/blas.c:1373)
GpuArrayException: ('Error in BLAS call', 11)

150 NameErrors. 
======================================================================
ERROR: pygpu.tests.test_elemwise.test_divmod('uint64', (50,), array(2.450000047683716, dtype=float32))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dokookchoe/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/tests/test_elemwise.py", line 254, in divmod_mixed
    out_g = divmod(g, elem)
  File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/_array.py", line 134, in __divmod__
    if not isinstance(other, array.GpuArray):
NameError: global name 'array' is not defined

Is anyone familiar with these errors? I have used the latest libgpuarray and followed all instructions except for one. I changed set(CMAKE_OSX_ARCHITECTURES i386 x86_64) to set(CMAKE_OSX_ARCHITECTURES ix86_64).

Thanks,
DK

**Comment by cdg720** [comment]
I looked into "NameError: global name 'array' is not defined". 
First, 'array' is not imported in _array.py. Second, 'array' doesn't have GpuArray but 'gpuarray' does.

I ran the followings in pygpu directory:
>>> import array
>>> array.GpuArray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'GpuArray'

>>> import gpuarray
>>> gpuarray.GpuArray
<type 'pygpu.gpuarray.GpuArray'>

Is 'array' supposed to be 'gpuarray'?

**Comment by abergeron** [comment]
There was an 'array.py' file that was renamed to '_array.py' because of name conflicts.  Maybe there is a leftover array.pyc file, which you should delete.

As for the GpuArrayException, from the sample you posted, it seems there are problems with your blas library.  The error just indicates that the blas library returned an error.

**Comment by cdg720** [comment]
Thank you for your answers.

I looked for array.pyc by executing "find / -name array.pyc" and got nothing. "ls" in pygpu returns __init__.py    blas.py        dtypes.py      gpuarray.h     gpuarray_api.h parser.py      scan.py        tools.pyc
__init__.pyc   blas.pyc       dtypes.pyc     gpuarray.py    numpy_compat.h parser.pyc     scan.pyc
_array.py      blas.so        elemwise.py    gpuarray.pyc   operations.py  reduction.py   tests
_array.pyc     blas_api.h     elemwise.pyc   gpuarray.so    operations.pyc reduction.pyc  tools.py.

When you say "blas library" do you mean clblas? This machine is a mac and I didn't install BLAS as the installation pages says OSX comes with the Accelerated framework.

**Comment by abergeron** [comment]
Yes I mean clBLAS.  It seems there is a problem with your intallation (which might just be that it is trying to run on the CPU and clBLAS doesn't like that).

Also, you have an old install of pygpu which does have the array.py file as evidenced by:

```
File "/Library/Python/2.7/site-packages/pygpu-0.2.1-py2.7-macosx-10.9-intel.egg/pygpu/array.py", line 134, in __divmod_
```

Get rid of that install and the problem should go away.

**Comment by cdg720** [comment]
Thanks for your help. I really appreciate it. I will look into my clBLAS installation. 

I don't have array.py in the pygpu directory. underscore character (_) right before array.py was italicizing it. I will make changes to escape some characters ('_', '*' and etc.).

**Comment by abergeron** [comment]
I get a `Floating Point Exception: 8` at some point when running the test suite on my machine.  However this is after the tests for elemwise operations which seem to be the source of your array problems.

I don't have much time to investigate this right now, but I should have some next week.
