### ISSUE TITLE
Unknown device error

### ISSUE THREAD

**Issue by serhii-havrylov** [Theano/libgpuarray#382]
Hi I've got Unknown device error with device=cuda0: 
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Unknown device error: 0
```
So far I figured out that pygpu/gpuarray.c makes call of gpucontext_init function from src/gpuarray_buffer.c. I managed to find that 44th line of code from that file is the source of error `res = ops->buffer_init(dev, flags, ret);` But unfortunately,  I can't find implementation of buffer_init. Could you give me a hint how to investigate this issue further?
I use cuda7.5, Ubuntu 14.04, Theano 0.9.0rc4

**Comment by nouiz** [comment]
Is cuda working without Theano? What is the output of this command in a
shell?

nvidia-smi

**Comment by serhii-havrylov** [comment]
Yes, it does work. As I said everything works with device=gpu0. Output of nvidia-smi is:

```
+------------------------------------------------------+                       
| NVIDIA-SMI 352.41     Driver Version: 352.41         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 0000:01:00.0     Off |                  N/A |
| 22%   57C    P0    72W / 250W |     20MiB /  6141MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 980     Off  | 0000:02:00.0     Off |                  N/A |
| 30%   39C    P0    40W / 195W |     15MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by nouiz** [comment]
WHich version of libgpuarray do you use? If you don't use the latest, make
sure to update. I call such a fix.

**Comment by serhii-havrylov** [comment]
Just have cloned the project from the github and reinstalled it. So I guess the version is 0.6.2. I still have the same issue.

**Comment by lamblin** [comment]
I think `buffer_init` points to [`cuda_init`](https://github.com/Theano/libgpuarray/blob/d0b9c2c8b07ae22ca48882b08bdc00be581f6dfb/src/gpuarray_buffer_cuda.c#L401) when the cuda back-end is used.

**Comment by abergeron** [comment]
Yes it does point to cuda_init.

**Comment by serhii-havrylov** [comment]
The problem is that [cuInit](https://github.com/Theano/libgpuarray/blob/master/src/gpuarray_buffer_cuda.c#L74) is not returning CUDA_SUCCESS. Apparently libgpuarray can't initialize the CUDA driver API. This is rather strange. Do you have any suggestions what I can try to do about it?

**Comment by nouiz** [comment]
What GPU do you use?

We got strange bug report when the cuda version is too old compared to the
GPU, when the cuda version don't support that GPU. Could it be your cases?

There is also strange thinks that happen when there is multiple cuda
version in the OS. I'd that your case?

Le lun. 20 mars 2017 11:32, serhii-havrylov <notifications@github.com> a
écrit :

**Comment by serhii-havrylov** [comment]
As you may see from the output of nvidia-smi that I have provided. I use GTX 980 Ti and GTX 980. Driver Version is [352.41](http://www.nvidia.com/Download/driverResults.aspx/90279/en-us) and it supports both of them. I use cuda 7.5 which was released after releasing both of the GPUs. To best of my knowledge, I have just one cuda version installed on my system.

**Comment by Hazarapet** [comment]
Same problem.is there any idea?

**Comment by nouiz** [comment]
Install libgpuarray dev version. It give in many cases much better error
message.

**Comment by Hazarapet** [comment]
Guys theano cache clear/purge helped for me.

**Comment by huguespoiget** [comment]
Got same problem here : 
`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Unknown device error: 0`

What is strange is that happens when I launch too many processes in the same time on the GPU. Each process alloc 340MiB on the GPU. When I reach  around 7500MiB / 11169MiB the new processes can't alloc anything and I get the above error.

Any idea why I can't use all the Memory on my GPU ? How to prevent those error to happens ? It seems also to prevent the GPU to use all the GPU-Util when a process crashes (still living processes can only use part of the GPU capacity after new processus crashes).

`Thu May  4 18:22:41 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 0000:01:00.0      On |                  N/A |
| 23%   40C    P8    18W / 250W |    342MiB / 11169MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     10975    G   /usr/lib/xorg/Xorg                              60MiB |
|    0     16955    G   /usr/lib/xorg/Xorg                              68MiB |
+-----------------------------------------------------------------------------+`

Thanks a lot

**Comment by abergeron** [comment]
You probably have fragmentation in the GPU memory.  Especially if you are also running graphics on the same card.

To avoid that you can try to set a preallocation of about 350MB for each of your processes which should avoid the fragmentation.

**Comment by Jackiexiao** [comment]
I have the same problem here , after I install cudnn.h
```
(merlin) jackie@jackie:~/study/pythonstudy$ theano-cache clear
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/jackie/anaconda3/envs/merlin/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/jackie/anaconda3/envs/merlin/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/jackie/anaconda3/envs/merlin/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Unknown device error: -1
```

**Comment by abergeron** [comment]
Try with the git master, the error messages should be more informative about why it failed to initialize.

**Comment by serhii-havrylov** [comment]
Hi @abergeron,

I run the code with the master version of libgpuarray and got next output:

**Comment by serhii-havrylov** [comment]
Hi @abergeron,

I run the code with the master version of libgpuarray and got next output:

```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9424)
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9115)
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13417)
GpuArrayException: cuInit: H�H���: (null)
```
Basically, It says the same as I found out before. Apparently libgpuarray can't initialize the CUDA driver API. This is rather strange because I can successfully run 1_Utilities/deviceQueryDrv nvidia example, which uses cuInit. Do you have any sugesstions?

**Comment by abergeron** [comment]
It looks like you get an unsupported error out of cuInit which is weird.  The problem may be because it's not loading the expected library, but that should still give you an intelligible error message.

Can you try with the abergeron/error_cuda branch?  It will try to print something useful for invalid errors.

**Comment by serhii-havrylov** [comment]
Hi @abergeron,

thanks for the suggestion. Unfortunately, I was not able to build abergeron/error_cuda branch due to the error:

```
In file included from ****/libgpuarray/src/gpuarray_buffer_cuda.c:4:0:
****/libgpuarray/src/private_cuda.h: In function ‘error_cuda’:
****/libgpuarray/src/private_cuda.h:49:5: error: incompatible types when assigning to type ‘struct error *’ from type ‘CUresult’
   e = cuGetErrorName(err, &name);
     ^
/home/sergii/Downloads/libgpuarray/src/private_cuda.h:48:16: warning: unused variable ‘e2’ [-Wunused-variable]
   CUresult e1, e2;
                ^
make[2]: *** [src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o] Error 1
make[1]: *** [src/CMakeFiles/gpuarray.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by abergeron** [comment]
Sorry about that, I fixed the compilation.  Can you try again?

**Comment by serhii-havrylov** [comment]
Here is the output:

```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/sergii/Desktop/python_venv/local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9424)
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9115)
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13417)
GpuArrayException: cuInit: Error -1: Bad error descriptor
```

**Comment by abergeron** [comment]
This is weird.  cuInit() returns -1 and it should never do that.  Are you sure that your driver install is ok?

**Comment by serhii-havrylov** [comment]
I am pretty much sure that driver is correctly installed. For example, I can run nvidia examples with driver calls.

**Comment by abergeron** [comment]
Can you run an instance of theano under pdb or something similar and run this command after the crash:

`cat /proc/<python pid>/maps | awk '{print $6}' | grep '\.so' | sort | uniq`

**Comment by abergeron** [comment]
Also can you run the same on the deviceQueryDrv binary (you would probably have to run it under gdb to pause the execution somewhere)?

**Comment by serhii-havrylov** [comment]
Here is the output for the python case:
[output.txt](https://github.com/Theano/libgpuarray/files/1120519/output.txt)

I am not familiar with cuda-gdb, will post the result when I figure out how to use it.

**Comment by abergeron** [comment]
You don't need cuda-gdb, regular gdb can also stop execution even if it can't debug the gpu code.

**Comment by abergeron** [comment]
I see that there are two libcuda, which might cause some confusion:
```
/usr/lib/x86_64-linux-gnu/libcuda.so.352.41
...
/usr/local/cuda-7.5/lib64/stubs/libcuda.so
```

I see that on my machine the stub is not loaded.  Do you have /usr/local/cuda-7.5/lib64/stubs in your LD_LIBRARY_PATH?

**Comment by serhii-havrylov** [comment]
Yes, I do have /usr/local/cuda-7.5/lib64/stubs in my LD_LIBRARY_PATH

**Comment by abergeron** [comment]
That is probably the cause of the problem then.  Can you try without it?

**Comment by abergeron** [comment]
Actually from what I read that is definitely the cause of the problem.  The stubs should only be used for linking when the real libraries are not available at build time.  They cannot be used at runtime so they should not be on LD_LIBRARY_PATH.

**Comment by serhii-havrylov** [comment]
I tried to run with LD_LIBRARY_PATH without /usr/local/cuda-7.5/lib64/stubs in it and got the same result. Here is relevant `cat /proc/<python pid>/maps | awk '{print $6}' | grep '\.so' | sort | uniq` output:
```
...
/lib/x86_64-linux-gnu/ld-2.19.so
/lib/x86_64-linux-gnu/libc-2.19.so
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/lib/x86_64-linux-gnu/libdl-2.19.so
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/liblzma.so.5.0.0
/lib/x86_64-linux-gnu/libm-2.19.so
/lib/x86_64-linux-gnu/libncursesw.so.5.9
/lib/x86_64-linux-gnu/libpng12.so.0.50.0
/lib/x86_64-linux-gnu/libpthread-2.19.so
/lib/x86_64-linux-gnu/librt-2.19.so
/lib/x86_64-linux-gnu/libssl.so.1.0.0
/lib/x86_64-linux-gnu/libtinfo.so.5.9
/lib/x86_64-linux-gnu/libutil-2.19.so
/lib/x86_64-linux-gnu/libz.so.1.2.8
/usr/lib/python2.7/lib-dynload/_csv.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_curses.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/datetime.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/future_builtins.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so
/usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
/usr/lib/x86_64-linux-gnu/libcuda.so.352.41
/usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.11.1
/usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
/usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7.0.0
/usr/lib/x86_64-linux-gnu/libhdf5.so.7.0.0
/usr/lib/x86_64-linux-gnu/libjbig.so.0
/usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
/usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
/usr/lib/x86_64-linux-gnu/libtiff.so.5.2.0
/usr/local/cuda-7.5/lib64/libcurand.so.7.5.18
/usr/local/lib/libgpuarray.so.2.1
/usr/local/lib/libopenblas_haswellp-r0.2.13.so
...
```

**Comment by elhoussinetalab** [comment]
same issue, to make things more weird, it used to work with no issue. I went to have lunch, came back to find this error! (No Joke!!) 

Kindly advise. 

`$ nvidia-smi 
Fri Sep 15 14:04:59 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.82                 Driver Version: 375.82                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 0000:01:00.0     Off |                  N/A |
| N/A   60C    P2    28W /  N/A |    178MiB /  6072MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1386    G   /usr/lib/xorg/Xorg                              95MiB |
|    0      7930    C   python3                                         79MiB |
+-----------------------------------------------------------------------------+`

error message: 

`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/hat/Desktop/Theano/theano/gpuarray/__init__.py", line 216, in <module>
    use(config.device)
  File "/home/hat/Desktop/Theano/theano/gpuarray/__init__.py", line 203, in use
    init_dev(device, preallocate=preallocate)
  File "/home/hat/Desktop/Theano/theano/gpuarray/__init__.py", line 90, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
`

**Comment by abergeron** [comment]
Try rebooting the machine, it helps sometimes.

**Comment by elhoussinetalab** [comment]
@abergeron that worked, but we need to track down this issue. it seems like an array is over filled or something. can someone advise.

**Comment by abergeron** [comment]
Weird errors are sometimes due to bugs in the driver, especially if a reboot fixes it.  I can't do anything about that.
