### ISSUE TITLE
GpuArrayException: ('Unknown GA error', 32767) 

### ISSUE THREAD

**Issue by jordanvrtanoski** [Theano/libgpuarray#385]
I have the following errors when running the tests on Macbook Pro 15" Retina with AMD Radeon R9 M370X Compute Engine running El Capitan 10.11.6

```
DEVICE="opencl0:2"  python -c "import pygpu;pygpu.test()"
.........
======================================================================
ERROR: pygpu.tests.test_blas.test_dot(666, 'float32', False, False, True, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/numpy/1.12.0/libexec/nose/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/test_blas.py", line 42, in dot
    gr = gblas.dot(gX, gY, gZ, overwrite_z=overwrite)
  File "pygpu/blas.pyx", line 63, in pygpu.blas.dot (pygpu/blas.c:2400)
  File "pygpu/blas.pyx", line 26, in pygpu.blas.pygpu_blas_rdot (pygpu/blas.c:1713)
GpuArrayException: ('Unknown GA error', 32767)

======================================================================
FAIL: pygpu.tests.test_elemwise.test_elemwise_f16(<built-in function add>, 'float16', 'float16', (50,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/numpy/1.12.0/libexec/nose/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/test_elemwise.py", line 123, in elemwise2_ops_array
    assert numpy.allclose(out_c, numpy.asarray(out_g))
AssertionError

======================================================================
FAIL: pygpu.tests.test_elemwise.test_elemwise_f16(<built-in function iadd>, 'float16', 'float16', (50,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/numpy/1.12.0/libexec/nose/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/support.py", line 39, in f
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg/pygpu/tests/test_elemwise.py", line 146, in ielemwise2_ops_array
    assert numpy.allclose(out_c, numpy.asarray(out_g), atol=1e-6)
AssertionError

----------------------------------------------------------------------
Ran 7048 tests in 16.114s
```

The clBLAS library is installed with home-brew and libgpuarray recompiled

```
homebrew/science/clblas: stable 2.6 (bottled)
Library containing BLAS functions written in OpenCL
https://github.com/clMathLibraries/clBLAS
/usr/local/Cellar/clblas/2.6 (20 files, 4MB) *
  Poured from bottle on 2017-03-18 at 21:33:20
From: https://github.com/Homebrew/homebrew-science/blob/master/clblas.rb
==> Dependencies
Build: make ✔, boost ✔
```

libgpuarray recompiled log:
```
mkdir -p Release
(cd Release && NUM_DEVS= DEV_NAMES= cmake .. -DCMAKE_BUILD_TYPE=Release)
-- The C compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for strlcat
-- Looking for strlcat - found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'check'
Tests disabled because Check was not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jordanvrtanoski/Yolo/libgpuarray/Release
(cd Release && make)
Scanning dependencies of target gpuarray
[  1%] Building C object src/CMakeFiles/gpuarray.dir/cache/lru.c.o
[  2%] Building C object src/CMakeFiles/gpuarray.dir/cache/twoq.c.o
[  4%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_types.c.o
[  5%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_error.c.o
[  7%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_util.c.o
[  8%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer.c.o
[ 10%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_blas.c.o
[ 11%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_collectives.c.o
[ 13%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array.c.o
[ 14%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_blas.c.o
[ 16%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_collectives.c.o
[ 17%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_kernel.c.o
[ 19%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_extension.c.o
[ 20%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_elemwise.c.o
[ 22%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_reduction.c.o
[ 23%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o
[ 25%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_cuda_cublas.c.o
[ 26%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_collectives_cuda_nccl.c.o
[ 27%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
[ 29%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_opencl_clblas.c.o
[ 30%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_opencl_clblast.c.o
[ 32%] Building C object src/CMakeFiles/gpuarray.dir/util/strb.c.o
[ 33%] Building C object src/CMakeFiles/gpuarray.dir/util/xxhash.c.o
[ 35%] Building C object src/CMakeFiles/gpuarray.dir/util/integerfactoring.c.o
[ 36%] Building C object src/CMakeFiles/gpuarray.dir/loaders/dyn_load.c.o
[ 38%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libcuda.c.o
[ 39%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libnvrtc.c.o
[ 41%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libcublas.c.o
[ 42%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libnccl.c.o
[ 44%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libopencl.c.o
[ 45%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libclblas.c.o
[ 47%] Building C object src/CMakeFiles/gpuarray.dir/loaders/libclblast.c.o
[ 48%] Linking C shared library ../../lib/libgpuarray.dylib
[ 50%] Built target gpuarray
Scanning dependencies of target gpuarray-static
[ 51%] Building C object src/CMakeFiles/gpuarray-static.dir/cache/lru.c.o
[ 52%] Building C object src/CMakeFiles/gpuarray-static.dir/cache/twoq.c.o
[ 54%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_types.c.o
[ 55%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_error.c.o
[ 57%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_util.c.o
[ 58%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer.c.o
[ 60%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_blas.c.o
[ 61%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_collectives.c.o
[ 63%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array.c.o
[ 64%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array_blas.c.o
[ 66%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array_collectives.c.o
[ 67%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_kernel.c.o
[ 69%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_extension.c.o
[ 70%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_elemwise.c.o
[ 72%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_reduction.c.o
[ 73%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_cuda.c.o
[ 75%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_blas_cuda_cublas.c.o
[ 76%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_collectives_cuda_nccl.c.o
[ 77%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_opencl.c.o
[ 79%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_blas_opencl_clblas.c.o
[ 80%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_blas_opencl_clblast.c.o
[ 82%] Building C object src/CMakeFiles/gpuarray-static.dir/util/strb.c.o
[ 83%] Building C object src/CMakeFiles/gpuarray-static.dir/util/xxhash.c.o
[ 85%] Building C object src/CMakeFiles/gpuarray-static.dir/util/integerfactoring.c.o
[ 86%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/dyn_load.c.o
[ 88%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libcuda.c.o
[ 89%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libnvrtc.c.o
[ 91%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libcublas.c.o
[ 92%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libnccl.c.o
[ 94%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libopencl.c.o
[ 95%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libclblas.c.o
[ 97%] Building C object src/CMakeFiles/gpuarray-static.dir/loaders/libclblast.c.o
[ 98%] Linking C static library ../../lib/libgpuarray-static.a
[100%] Built target gpuarray-static
(cd Release && sudo make install)
Password:
[ 50%] Built target gpuarray
[100%] Built target gpuarray-static
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/gpuarray/array.h
-- Up-to-date: /usr/local/include/gpuarray/blas.h
-- Up-to-date: /usr/local/include/gpuarray/collectives.h
-- Up-to-date: /usr/local/include/gpuarray/buffer.h
-- Up-to-date: /usr/local/include/gpuarray/buffer_blas.h
-- Up-to-date: /usr/local/include/gpuarray/buffer_collectives.h
-- Installing: /usr/local/include/gpuarray/abi_version.h
-- Up-to-date: /usr/local/include/gpuarray/config.h
-- Up-to-date: /usr/local/include/gpuarray/elemwise.h
-- Up-to-date: /usr/local/include/gpuarray/error.h
-- Up-to-date: /usr/local/include/gpuarray/extension.h
-- Up-to-date: /usr/local/include/gpuarray/ext_cuda.h
-- Up-to-date: /usr/local/include/gpuarray/kernel.h
-- Up-to-date: /usr/local/include/gpuarray/types.h
-- Up-to-date: /usr/local/include/gpuarray/util.h
-- Installing: /usr/local/lib/libgpuarray.2.0.dylib
-- Up-to-date: /usr/local/lib/libgpuarray.2.dylib
-- Up-to-date: /usr/local/lib/libgpuarray.dylib
-- Installing: /usr/local/lib/libgpuarray-static.a
python setup.py build_ext --inplace
running build_ext
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/gpuarray.so -> pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/blas.so -> pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/_elemwise.so -> pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/collectives.so -> pygpu
```

python setup.py install 

```
running install
running bdist_egg
running egg_info
writing requirements to pygpu.egg-info/requires.txt
writing pygpu.egg-info/PKG-INFO
writing top-level names to pygpu.egg-info/top_level.txt
writing dependency_links to pygpu.egg-info/dependency_links.txt
reading manifest file 'pygpu.egg-info/SOURCES.txt'
writing manifest file 'pygpu.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
copying pygpu/version.py -> build/lib.macosx-10.11-x86_64-2.7/pygpu
running build_ext
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/_array.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/_elemwise.c -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/_elemwise.so -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/blas.c -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/blas.so -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/blas_api.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/collectives.c -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/collectives.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/collectives.so -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/collectives_api.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/dtypes.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/elemwise.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/gpuarray.c -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/gpuarray.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/gpuarray.so -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/gpuarray_api.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/numpy_compat.h -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/operations.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/reduction.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
creating build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/main.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/support.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_blas.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_elemwise.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_gpu_ndarray.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_operations.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_reduction.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tests/test_tools.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu/tests
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/tools.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
copying build/lib.macosx-10.11-x86_64-2.7/pygpu/version.py -> build/bdist.macosx-10.11-x86_64/egg/pygpu
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/_array.py to _array.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/dtypes.py to dtypes.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/elemwise.py to elemwise.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/operations.py to operations.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/reduction.py to reduction.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/main.py to main.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/support.py to support.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_blas.py to test_blas.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_elemwise.py to test_elemwise.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_gpu_ndarray.py to test_gpu_ndarray.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_operations.py to test_operations.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_reduction.py to test_reduction.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tests/test_tools.py to test_tools.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/tools.py to tools.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/version.py to version.pyc
creating stub loader for pygpu/gpuarray.so
creating stub loader for pygpu/blas.so
creating stub loader for pygpu/_elemwise.so
creating stub loader for pygpu/collectives.so
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/gpuarray.py to gpuarray.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/blas.py to blas.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/_elemwise.py to _elemwise.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pygpu/collectives.py to collectives.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pygpu.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pygpu.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pygpu.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pygpu.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pygpu.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pygpu.__init__: module references __file__
pygpu.tests.main: module references __file__
creating 'dist/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg
removing '/usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg
Extracting pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg to /usr/local/lib/python2.7/site-packages
pygpu 0.6.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/pygpu-0.6.2-py2.7-macosx-10.11-x86_64.egg
Processing dependencies for pygpu==0.6.2
Searching for Mako==1.0.0
Best match: Mako 1.0.0
Processing Mako-1.0.0-py2.7.egg
Mako 1.0.0 is already the active version in easy-install.pth
Installing mako-render script to /usr/local/bin

Using /Library/Python/2.7/site-packages/Mako-1.0.0-py2.7.egg
Searching for MarkupSafe==0.23
Best match: MarkupSafe 0.23
MarkupSafe 0.23 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages
Finished processing dependencies for pygpu==0.6.2
```

Following are the python packages installed in the environment
```
actdiag==0.5.4
alabaster==0.7.8
appnope==0.1.0
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.5.0
blockdiag==1.5.3
brewer2mpl==1.4.1
cashew==0.2.7
certifi==2016.8.31
chardet==2.3.0
click==6.6
colorama==0.3.7
configparser==3.5.0
cycler==0.10.0
Cython==0.25.2
dask==0.14.0
decorator==4.0.11
dexy==1.0.15
dexy-viewer==0.0.5
dlib==19.4.0
dnspython==1.14.0
docker-py==1.8.1
docutils==0.12
easyzone==1.2.2
entrypoints==0.2.2
feedparser==5.1.3
Flask==0.11
Flask-Mako==0.4
flask-mongoengine==0.7.5
Flask-Script==2.0.5
Flask-WTF==0.12
funcparserlib==0.3.6
funcsigs==1.0.2
functools32==3.2.3.post2
gdata==2.0.18
gevent==1.0.1
ggplot==0.11.5
greenlet==0.4.5
gunicorn==19.1.1
imagesize==0.7.1
inflection==0.3.1
ipaddress==1.0.16
ipykernel==4.4.1
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.1.1
Keras==2.0.1
lxml==3.4.4
Mako==1.0.0
Markdown==2.6.6
MarkupSafe==0.23
matplotlib==2.0.0
mercurial==3.3
mistune==0.7.3
mock==2.0.0
mongoengine==0.10.6
nbconvert==4.2.0
nbformat==4.1.0
networkx==1.11
newrelic==2.56.0.42
nose==1.3.7
notebook==4.2.2
numpy==1.12.0
nwdiag==1.0.4
olefile==0.44
pandas==0.19.0
passlib==1.6.2
pathlib2==2.1.0
patsy==0.4.1
pbr==2.0.0
pexpect==4.2.0
pickleshare==0.7.4
PIL==1.1.7
Pillow==4.0.0
ply==3.8
prompt-toolkit==1.0.7
protobuf==3.2.0
psutil==2.1.3
psycogreen==1.0
psycopg2==2.5.4
ptyprocess==0.5.1
pyasn1==0.1.8
PyChart==1.39
pycrypto==2.6.1
PyDAV==0.21
pydot==1.0.28
pydotplus==2.0.2
pyexchange==0.6
Pygments==2.0.2
pygpu==0.6.2
pymongo==3.2.2
pyparsing==2.2.0
pyPdf==1.13
pyserial==3.0.1
pysnmp==4.2.5
pyst2==0.5.0
Python-Chart==1.39
python-clickatell==0.1.3
python-dateutil==2.6.0
python-ldap==2.4.18
python-modargs==1.7
python-ntlm3==1.0.2
python-openid==2.2.5
python-stdnum==1.0
python-webdav==0.4
pytz==2016.10
pyusb==1.0.0rc1
PyWebDAV==0.9.8
PyXML==0.8.4
PyYAML==3.11
pyzmq==15.4.0
qrcode==5.2.2
qtconsole==4.2.1
reportlab==3.1.8
requests==2.10.0
requests-ntlm==0.2.0
robotframework==3.0
robotframework-selenium2library==1.7.4
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.19.0
selenium==2.53.1
simplegeneric==0.8.1
simplejson==3.6.5
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.0
Sphinx==1.4.2
sphinx-patchqueue==0.4.0
sphinx-rtd-theme==0.1.9
sphinxcontrib-actdiag==0.8.5
sphinxcontrib-blockdiag==1.5.5
sphinxcontrib-httpdomain==1.5.0
sphinxcontrib-nwdiag==0.9.5
sphinxcontrib-plantuml==0.8.1
statsmodels==0.6.1
stevedore==1.21.0
subprocess32==3.2.7
TBB==0.1
tensorflow==1.0.1
terminado==0.6
Theano==0.9.0rc4
toolz==0.8.2
tornado==4.4.1
traitlets==4.2.2
unittest2==0.8.0
vatnumber==1.2
vboxapi==1.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
vobject==0.8.1rc0
wcwidth==0.1.7
web.py==0.38
webcolors==1.5
websocket-client==0.37.0
Werkzeug==0.11.10
widgetsnbextension==1.2.6
wkhtmltopdf==0.2
WTForms==2.1
xlwt==0.7.5
ZSI==2.0rc3
```

**Comment by nouiz** [comment]
We don't have time to support OpenCL for now. It also don't work on Theano,
too many ops don't support it. So unless you are ready to help us make this
work, I would recommend to not use it.

Le sam. 18 mars 2017 13:53, Jordan Vrtanoski <notifications@github.com> a
écrit :
