### ISSUE TITLE
setup.py build fails due to "requires"

### ISSUE THREAD

**Issue by admcrae** [Theano/libgpuarray#392]
When attempting to build the latest master (as of this posting) of libgpuarray, I get the following error on `python3 setup.py build`:
```
Traceback (most recent call last):
  File "setup.py", line 147, in <module>
    requires=['mako>=0.7', 'six'],
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.5/distutils/dist.py", line 1208, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.5/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '>=0.7'
```
A quick Google search suggests that the change in #388 from `install_requires` to `requires` is a likely culprit.

Using release 0.6.2 resolves the problem.

**Comment by nouiz** [comment]
fixed. thanks for the report.
