### ISSUE TITLE
Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by EgZvor** [Theano/libgpuarray#397]
I spent 10 hours trying to make it work. I think I even got it once by some manipulation with environmental variables, but then I restarted the console and it stopped working again. That's the issue when I'm trying to import theano.
I use python 3.5 on Windows 10 with conda installation in environment called tensorflow (sic).

`Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\dnn.py", line 157, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\dnn.py", line 130, in _dnn_check_version
    v = version()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gpuarray\dnn.py", line 338, in version
    profile=False)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\gof\cmodule.py", line 2295, in compile_str
    compile_stderr = decode(p_out[1])
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\theano\compat\__init__.py", line 43, in decode
    return x.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 238: invalid continuation byte`

**Comment by EgZvor** [comment]
CUDA V8.0.60
Output of nvidia-smi
![image](https://cloud.githubusercontent.com/assets/11237935/24593247/06cea67c-182a-11e7-848b-eb199dcaba54.png)

**Comment by EgZvor** [comment]
I solved it, it's kinda ridiculous. So I have cyrillic symbols in Username and [that line](https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L2295) wouldn't work. I simply did
`compile_stderr = decode(p_out[1].decode('cp1251').encode('utf-8'))`
And now it finally works.
Although, I still get
```
Can not use cuDNN on context None: Device not supported
Mapped name None to device cuda0: GeForce GT 630M (0000:01:00.0)
```
for whatever reason. theanorc is loaded as can be seen by other configs and in that I have
```[global]
floatX = float32
device = cuda0
print_active_device = True```
