### ISSUE TITLE
GpuArrayException: unknown error / unknown device error

### ISSUE THREAD

**Issue by Farbdose** [Theano/libgpuarray#420]
**OnHold after computer restart no graphics output anymore - potential hardware failure**

---------------

I have an unknown error and no real idea on how to debug it:
Same code is running fine with similar setup on linux...

**Setup:**

    OS: Windows 10 (64 bit)
    Python 2.7.13 | Anaconda custom (64-bit)(default, Dec 19 2016, 13:29:36) 
    MSC v.1500 64 bit (AMD64)
    Theano: 0.9.0
    Pygpu: 0.6.4

**.theanorc**
```
[global] 
floatX=float32 
device=cuda
print_active_device=True 
mode=FAST_RUN
optimizer_including=cudnn:local_remove_all_asser:conv_meta:conv_fft

[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

[dnn] 
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

[dnn.conv] 
algo_fwd=time_on_shape_change
algo_bwd_data=time_on_shape_change 
algo_bwd_filter=time_on_shape_change 
precision=as_input 

[gpuarray]
sched=multi

[nvcc]
fastmath = True
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

[blas]
ldflags =-LC:\\OpenBlas -lopenblas
```

**The Error**
```
Traceback (most recent call last):
  File "C:\Users\Farbdose\AutoEncoder.py", line 691, in training
    initial_epoch=0, callbacks=callbacks)
  File "C:\Anaconda2\lib\site-packages\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1877, in fit_generator
    class_weight=class_weight)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1621, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 1122, in __call__
    return self.function(*inputs)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Anaconda2\lib\site-packages\theano\gof\link.py", line 174, in raise_with_op
    detailed_err_msg += "\nOutputs clients: %s\n" % clients
  File "C:\Anaconda2\lib\site-packages\theano\gof\graph.py", line 184, in __repr__
    return str(self)
  File "C:\Anaconda2\lib\site-packages\theano\gof\graph.py", line 181, in __str__
    return op_as_string(self.inputs, self)
  File "C:\Anaconda2\lib\site-packages\theano\gof\graph.py", line 1259, in op_as_string
    strs = as_string(i, op.inputs, leaf_formatter, node_formatter)
  File "C:\Anaconda2\lib\site-packages\theano\gof\graph.py", line 1339, in as_string
    return [describe(output) for output in o]
  File "C:\Anaconda2\lib\site-packages\theano\gof\graph.py", line 1337, in describe
    return leaf_formatter(r)
  File "C:\Anaconda2\lib\site-packages\theano\gpuarray\type.py", line 606, in __str__
    return "GpuArrayConstant{%s}" % np_data
  File "pygpu\gpuarray.pyx", line 2148, in pygpu.gpuarray.GpuArray.__str__ (pygpu/gpuarray.c:28699)
  File "C:\Anaconda2\lib\site-packages\numpy\core\numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
  File "pygpu\gpuarray.pyx", line 1664, in pygpu.gpuarray.GpuArray.__array__ (pygpu/gpuarray.c:21612)
  File "pygpu\gpuarray.pyx", line 1371, in pygpu.gpuarray._pygpu_as_ndarray (pygpu/gpuarray.c:18318)
  File "pygpu\gpuarray.pyx", line 384, in pygpu.gpuarray.array_read (pygpu/gpuarray.c:6919)
GpuArrayException: unknown error
```

After trying to import theano again I now get

```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 175, in <module>
    use(config.device)
  File "C:\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 162, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 65, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Unknown device error: -1
```

**Comment by nouiz** [comment]
Can you try pygpu 0.6.5? It should give a better error message.

conda install -c forge pygpu=0.6.5

**Comment by Farbdose** [comment]
Sorry for not closing this sooner, as stated at the beginning this was indeed an unknown device error:
my graphics card died but was somehow still able to work until pc restart so I could copy and past the error...
