### ISSUE TITLE
Could not load "libcuda.so"

### ISSUE THREAD

**Issue by QueenT** [Theano/libgpuarray#431]
When I try to run this command `THEANO_FLAGS="device=cuda0" python -c "import theano"`, I got following error message:

> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9417)
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9108)
  File "pygpu/gpuarray.pyx", line 1060, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13470)
GpuArrayException: Could not load "libcuda.so": libcuda.so: cannot open shared object file: No such file or directory: 0

However, everything acts normal if I just switch back to the old backend. libgpuarray and pygpu are installed following the instructions.

**Comment by nouiz** [comment]
How did you fix this? To help other people that would have the same problem.

**Comment by QueenT** [comment]
Hi,

Actually I didn't really fix this problem.

I  installed anaconda and set up everything through conda then this problem
is gone.

Before this I was using original Python pip, so I compiled and install
libgpuarray/pygpu myself. I didn't find out the cause or other solution
than simply switching to conda.

2017年5月10日 23:48，"Frédéric Bastien" <notifications@github.com>写道：

> How did you fix this? To help other people that would have the same
> problem.
>

**Comment by nouiz** [comment]
Thanks for the update

**Comment by pogilon** [comment]
I have having the same problem. However, I used conda and still having it.

GpuArrayException: Could not load "libcuda.so": libcuda.so: cannot open shared object file: No such file or directory

**Comment by nouiz** [comment]
Which version of libgpuarray do you use? Make sure to update to 0.7.5, it fixed problems like this in corner case.

**Comment by pietromarchesi** [comment]
I am having the same problem, even with a fresh conda environment (Python 3.6.4) in which I do `conda install pygpu theano`. With the stable conda installs I get theano 0.9.0 and pygpu 0.6.9. 

When I run the gpu test, I get pretty much the same traceback. 

> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/pmarche1/miniconda3/envs/3theanoenv/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/pmarche1/miniconda3/envs/3theanoenv/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/pmarche1/miniconda3/envs/3theanoenv/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__
pygpu.gpuarray.GpuArrayException: b'Could not load "libcuda.so": libnvidia-fatbinaryloader.so.384.66: cannot open shared object file: No such file or directory'

If I run `locate libcuda.so` I get

> /usr/lib64/libcuda.so
/usr/lib64/libcuda.so.1
/usr/lib64/nvidia/libcuda.so
/usr/lib64/nvidia/libcuda.so.1
/usr/lib64/nvidia/libcuda.so.384.66
/usr/local/cuda-8.0/doc/man/man7/libcuda.so.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-8.0-orig/doc/man/man7/libcuda.so.7

Is something wrong there? My `.theanorc` is 

``` 
[cuda]
root=/usr/local/cuda-8.0

[global]
device = cuda
floatX = float32
```

**Comment by taozeyi** [comment]
I have same issue any one can fix this? thanks
