### ISSUE TITLE
Is pygpu supported by Nvidia driver 381.09? HELP!!

### ISSUE THREAD

**Issue by xn8812** [Theano/libgpuarray#441]
Hi, I am using keras with theano backend in a docker environment. My nvidia driver is upgraded to version 381.09. However, when I import keras, it reports an error message:

Using Theano backend.
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
File "/opt/conda/lib/python2.7/site-packages/theano/gpuarray/init.py", line 164, in 
use(config.device)
File "/opt/conda/lib/python2.7/site-packages/theano/gpuarray/init.py", line 151, in use
init_dev(device)
File "/opt/conda/lib/python2.7/site-packages/theano/gpuarray/init.py", line 60, in init_dev
sched=config.gpuarray.sched)
File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.cinit (pygpu/gpuarray.c:13468)
GpuArrayException: Unknown device error: 0

I wonder if this error is because the pygpu library is not supported by the new nvidia driver, or is due to some other reasons?

Thanks very much!!

**Comment by xn8812** [comment]
Running nvidia-smi gives me:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.09                 Driver Version: 381.09                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 28%   46C    P0    83W / 250W |      0MiB /  6081MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 28%   46C    P0    83W / 250W |      0MiB /  6082MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:83:00.0     Off |                  N/A |
| 27%   44C    P0    82W / 250W |      0MiB /  6082MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:84:00.0     Off |                  N/A |
|  0%   37C    P0    66W / 250W |      0MiB /  6082MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |

**Comment by abergeron** [comment]
Can you try to 0.6.5?

**Comment by abergeron** [comment]
Since there is no answer I will assume this works.  Please reopen if there are still problems with 0.6.9 or 0.7.x
