### ISSUE TITLE
pygpu.test() is broken in v0.6.6

### ISSUE THREAD

**Issue by ksze** [Theano/libgpuarray#458]
Somebody decided to remove the `import nose.plugins.builtin` in pygpu/tests/main between v0.6.5 and v0.6.6, and that completely broke pygpu.test():

```
$ DEVICE=opencl0:0 python -c "import pygpu; pygpu.test()"
pygpu is installed in /home/ksze/.virtualenvs/lasagne/local/lib/python2.7/site-packages/pygpu-0.6.6-py2.7-linux-x86_64.egg/pygpu
NumPy version 1.13.0
NumPy relaxed strides checking option: True
NumPy is installed in /home/ksze/.virtualenvs/lasagne/local/lib/python2.7/site-packages/numpy
Python version 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
nose version 1.3.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ksze/.virtualenvs/lasagne/local/lib/python2.7/site-packages/pygpu-0.6.6-py2.7-linux-x86_64.egg/pygpu/__init__.py", line 22, in test
    main.NoseTester(package=tests).test()
  File "/home/ksze/.virtualenvs/lasagne/local/lib/python2.7/site-packages/pygpu-0.6.6-py2.7-linux-x86_64.egg/pygpu/tests/main.py", line 123, in test
    capture, knownfailure)
  File "/home/ksze/.virtualenvs/lasagne/local/lib/python2.7/site-packages/pygpu-0.6.6-py2.7-linux-x86_64.egg/pygpu/tests/main.py", line 73, in prepare_test_args
    plugins += [p() for p in nose.plugins.builtin.plugins]
AttributeError: 'module' object has no attribute 'builtin'
```

UPDATE: This seems to be the relevant commit: https://github.com/Theano/libgpuarray/commit/5b54f6d753805f1ca3f6a1607a49ac6c47da62c5?diff=unified#diff-ad5a988f809ca5c3ddcfea526220c9a7L2

**Comment by abergeron** [comment]
You're right.  This should fix it: #459
