### ISSUE TITLE
pygpu doesn't properly work after installation in Windows(Anaconda)

### ISSUE THREAD

**Issue by Red-Pheonix** [Theano/libgpuarray#510]
I installed theano and pygpu in Anaconda in a separete environment. The installation was successful and without errors but when I ran pygpu.test() it shows this-

```
>   pygpu is installed in F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu
>   NumPy version 1.13.1
>   NumPy relaxed strides checking option: True
>   NumPy is installed in F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\numpy
>   Python version 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:00:41) [MSC v.1900 32 bit (Intel)]
>   nose version 1.3.7
>   EEEEEE
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_blas.py", line 5, in <module>
>       from .support import (guard_devsup, gen_gpuarray, context)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_elemwise.py", line 13, in <module>
>       from .support import (guard_devsup, context, gen_gpuarray, check_meta_content)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_gpu_ndarray.py", line 15, in <module>
>       from .support import (guard_devsup, check_meta, check_flags, check_all,
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_operations.py", line 4, in <module>
>       from .support import (gen_gpuarray, context, SkipTest)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_reduction.py", line 8, in <module>
>       from .support import (guard_devsup, check_meta_content, context, gen_gpuarray,
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ======================================================================
>   ERROR: Failure: GpuArrayException (Error loading library: 0)
>   ----------------------------------------------------------------------
>   Traceback (most recent call last):
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\failure.py", line 39, in runTest
>       raise self.exc_val.with_traceback(self.tb)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
>       addr.filename, addr.module)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 47, in importFromPath
>       return self.importFromDir(dir_path, fqname)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\nose\importer.py", line 94, in importFromDir
>       mod = load_module(part_fqname, fh, filename, desc)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 234, in load_module
>       return load_source(name, filename, file)
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\imp.py", line 172, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 675, in _load
>     File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>     File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\test_tools.py", line 5, in <module>
>       from .support import (guard_devsup, rand, check_flags, check_meta, check_all,
>     File "F:\Software_Development\Anaconda\envs\dplrning\lib\site-packages\pygpu\tests\support.py", line 32, in <module>
>       context = gpuarray.init(get_env_dev())
>     File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>     File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>     File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
>   pygpu.gpuarray.GpuArrayException: Error loading library: 0
>
>   ----------------------------------------------------------------------
>   Ran 6 tests in 0.008s
>
>   FAILED (errors=6)
>   <nose.result.TextTestResult run=6 errors=6 failures=0>
```

I searched around the internet but none of the solutions worked for me. So I must ask here. Here are  some additional details-

>Windows 10 Pro X64
> Python 3.6(Anaconda)
>Theano(0.9.0)
>pygpu(0.6.2)
>CUDA(8.0.61)

**Comment by abergeron** [comment]
There should be a more recent version of pygpu (0.6.7 at least) available on the conda default channel.

It fixes a lot of problems with library loading on Windows, so try that first.

**Comment by nouiz** [comment]
No news and should be fixed in newer release, so closing.
