### ISSUE TITLE
980GTX cuda tests failing

### ISSUE THREAD

**Issue by lukemetz** [Theano/libgpuarray#52]
Hello,
Wanted to report an error I had and some a potential workaround when installing and running tests. (The tests fail both for cuda and opencl, but this issue focuses on cuda.)

My system:
* 980gtx with 346.59 drivers
* cuda 7
* ubuntu 15.04

The tests that fail are in test_blas.py.
`
In an effort to workaround, I found: https://groups.google.com/forum/#!topic/theano-users/nEr9PqQF880, and bumped up the version number of the PTX from 4.0 to 4.2 and that seems to fix issues locally for cuda only, but I have no idea the consequences.

The cuda errors look like with 315 of them:

    ======================================================================
    ERROR: pygpu.tests.test_blas.test_ger(4, 5, 'float32', 'f', 1, 1, False, False)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/luke/Apps/libgpuarray/pygpu/tests/test_blas.py", line 154, in ger
        gr = gblas.ger(1.0, gX, gY, gA, overwrite_a=overwrite)
      File "pygpu/blas.pyx", line 130, in pygpu.blas.ger (pygpu/blas.c:2633)
        pygpu_blas_rger(alpha, X, Y, A, 0)
      File "pygpu/blas.pyx", line 43, in pygpu.blas.pygpu_blas_rger (pygpu/blas.c:1561)
        raise GpuArrayException(GpuArray_error(&X.ga, err), err)
    GpuArrayException: ('Device does not support operation', 8)

    ----------------------------------------------------------------------

The opencl errors look like with 315 of them:

    ERROR: pygpu.tests.test_blas.test_gemv((32, 32), 'float32', 'f', False, False, 1, False, True, 0, 0)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/luke/Apps/libgpuarray/pygpu/tests/support.py", line 39, in f
        func(*args, **kwargs)
      File "/home/luke/Apps/libgpuarray/pygpu/tests/test_blas.py", line 61, in gemv
        overwrite_y=overwrite)
      File "pygpu/blas.pyx", line 72, in pygpu.blas.gemv (pygpu/blas.c:1925)
        pygpu_blas_rgemv(transA, alpha, A, X, beta, Y, 0)
      File "pygpu/blas.pyx", line 27, in pygpu.blas.pygpu_blas_rgemv (pygpu/blas.c:1317)
        raise GpuArrayException(GpuArray_error(&A.ga, err), err)
    GpuArrayException: ('Device does not support operation', 8)
    ERROR: pygpu.tests.test_blas.test_gemv((32, 32), 'float32', 'f', False, False, 1, False, True, 0, 0)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/luke/Apps/libgpuarray/pygpu/tests/support.py", line 39, in f
        func(*args, **kwargs)
      File "/home/luke/Apps/libgpuarray/pygpu/tests/test_blas.py", line 61, in gemv
        overwrite_y=overwrite)
      File "pygpu/blas.pyx", line 72, in pygpu.blas.gemv (pygpu/blas.c:1925)
        pygpu_blas_rgemv(transA, alpha, A, X, beta, Y, 0)
      File "pygpu/blas.pyx", line 27, in pygpu.blas.pygpu_blas_rgemv (pygpu/blas.c:1317)
        raise GpuArrayException(GpuArray_error(&A.ga, err), err)
    GpuArrayException: ('Device does not support operation', 8)

If you would like any more information or testing please let me know! Thanks!

**Comment by nouiz** [comment]
Sorry for the delay. For OpenCL, of you want blas (needed for dot product),
you must install clBLAS.

**Comment by abergeron** [comment]
Are you sure you are testing with cuda for the first block?

By default the tests are run on opencl and the cuda toolkit does have an opencl interface that gets picked up.  To test for cuda use DEVICE=cuda0 (or cuda1, cuda2) as an environment variable for the tests.

**Comment by abergeron** [comment]
Since there are no answers I will consider this fixed as I can't reproduce.
