### ISSUE TITLE
Better error message for driver too old with CUDA 9.1

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#560]
To help us lower user support we need a better error message. Currently with driver good enought for CUDA 9.0 (384.90), you get this error when tring to use CUDA 9.1:

```
$ THEANO_FLAGS=device=cuda python -c "import theano"
Using cuDNN version 7002 on context None
ERROR 11: cublasCreate: (cublas) Library not initialized.
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/u/bastienf/repos/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/u/bastienf/repos/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/u/bastienf/repos/theano/gpuarray/__init__.py", line 159, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm (pygpu/blas.c:3538)
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:2028)
GpuArrayException: ('cublasCreate: (cublas) Library not initialized.', 11)

$ nvidia-smi 
Tue Dec 19 14:57:15 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 520      Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   42C    P0    N/A /  N/A |    347MiB /   964MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   37C    P8    14W / 250W |      2MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

```

**Comment by nouiz** [comment]
Maybe we could just extend the error message with an hint like:
"Maybe your driver is too old for your cuda version". This would guide the user in the right direction.

**Comment by nouiz** [comment]
done in https://github.com/Theano/libgpuarray/pull/561
