### ISSUE TITLE
'Could not load "nvrtc64_70.dll":

### ISSUE THREAD

**Issue by PeeJay** [Theano/libgpuarray#562]
I have installed pygpu + libgpuarray (0.7.5) in windows 10 x64 via miniconda. Cuda 8 is in its default path, but it's not being detected. I tried both the conda and conda-forge packages but that didn't help. Any suggestions?
```
(C:\temp\Miniconda3) P:\temp\neural-enhance>conda install -c conda-forge pygpu
Solving environment: done

## Package Plan ##

  environment location: C:\temp\Miniconda3

  added / updated specs:
    - pygpu


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgpuarray-0.7.5          |           vc14_0         317 KB  conda-forge
    openssl-1.0.2n             |           vc14_0         5.4 MB  conda-forge
    certifi-2017.11.5          |           py36_0         197 KB  conda-forge
    ca-certificates-2017.11.5  |                0         182 KB  conda-forge
    pygpu-0.7.5                |           py36_0         575 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.6 MB

The following packages will be UPDATED:

    ca-certificates: 2017.08.26-h94faf87_0    --> 2017.11.5-0      conda-forge
    certifi:         2017.11.5-py36hb8ac631_0 --> 2017.11.5-py36_0 conda-forge
    libgpuarray:     0.7.5-hfa6e2cd_0         --> 0.7.5-vc14_0     conda-forge [vc14]
    openssl:         1.0.2n-h74b6da3_0        --> 1.0.2n-vc14_0    conda-forge [vc14]
    pygpu:           0.7.5-py36hfa6e2cd_0     --> 0.7.5-py36_0     conda-forge

Proceed ([y]/n)?


Downloading and Extracting Packages
libgpuarray 0.7.5: ############################################################################################ | 100%
openssl 1.0.2n: ############################################################################################### | 100%
certifi 2017.11.5: ############################################################################################ | 100%
ca-certificates 2017.11.5: #################################################################################### | 100%
pygpu 0.7.5: ################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(C:\temp\Miniconda3) P:\temp\neural-enhance>python -c "import pygpu; pygpu.test()"
pygpu is installed in C:\temp\Miniconda3\lib\site-packages\pygpu
NumPy version 1.13.3
NumPy relaxed strides checking option: True
NumPy is installed in C:\temp\Miniconda3\lib\site-packages\numpy
Python version 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
EEEEEEEE
======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_basic.py", line 5, in <module>
    from .support import (gen_gpuarray, context)
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_blas.py", line 5, in <module>
    from .support import (guard_devsup, gen_gpuarray, context)
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_collectives.py", line 15, in <module>
    from pygpu.tests.support import (check_all, gen_gpuarray, context as ctx)
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_elemwise.py", line 13, in <module>
    from .support import (guard_devsup, context, gen_gpuarray, check_meta_content)
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_gpu_ndarray.py", line 15, in <module>
    from .support import (guard_devsup, check_meta, check_flags, check_all,
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_operations.py", line 4, in <module>
    from .support import (gen_gpuarray, context, SkipTest)
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_reduction.py", line 8, in <module>
    from .support import (guard_devsup, check_meta_content, context, gen_gpuarray,
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'

======================================================================
ERROR: Failure: GpuArrayException (b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\temp\Miniconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\temp\Miniconda3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\temp\Miniconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\temp\Miniconda3\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\temp\Miniconda3\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\test_tools.py", line 3, in <module>
    from .support import context, gen_gpuarray
  File "C:\temp\Miniconda3\lib\site-packages\pygpu\tests\support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu\gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'
```
----------------------------------------------------------------------
Ran 8 tests in 0.007s

FAILED (errors=8)

**Comment by abergeron** [comment]
I would check these things in order:

1) What version of the driver is installed?  Check with nvidia-smi.  It should be higher than 375.XX.
2) Is the cuda directory in %PATH%? The cuda installer should do that for you, but something may have gone wrong.

**Comment by PeeJay** [comment]
It was missing from PATH. CUDAPATH was set so I didn't think to check PATH.
Thanks!

**Comment by PeeJay** [comment]
I just installed Cuda on another computer, and the installer didn't add itself to %PATH% there either. Perhaps on windows %CUDA_PATH% should be used to find the runtime as everyone with a new install will have the same trouble it seems.

**Comment by abergeron** [comment]
On all the machines we've tested the folder containing the DLLs where either in %PATH% or the DLLs themselves were registered so that the dynamic linker can find them.

We did try that with cuda 8 and 9 so I don't why you are getting different results here.

**Comment by nouiz** [comment]
Did you reboot/logout after the installation?

**Comment by duguyeren** [comment]
Hi, I have the same problem. Have you already solve it? I install the cuda 9.1 but pygpu wants to load nvrtc64_70.dll.  Only nvrtc64_91.dll was found in my computer.  I confirm that I don't have installed cuda 7.0.

**Comment by lamblin** [comment]
Which version of the drivers do you have installed? Can you update them?

**Comment by duguyeren** [comment]
The driver version is 397.31,and  I have updated them.  I gave up using it on windows. Linux is a better choice.
