### ISSUE TITLE
Can not use cuDNN on context None: Device not supported

### ISSUE THREAD

**Issue by ashleshsortee** [Theano/libgpuarray#566]
Please help: Getting below error. Is Nvidia GeForce 820M not supported or there is other problem?

(env_name35) C:\Users\ashlesh\Desktop>python test.py
Can not use cuDNN on context None: Device not supported
Mapped name None to device cuda: GeForce 820M (0000:09:00.0)
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    f = function([], T.exp(x))
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\compile\function_module.py", line 1839, in orig_function
    name=name)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\compile\function_module.py", line 1519, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 99, in __call__
    return self.optimize(fgraph)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 88, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 242, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 88, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 242, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gof\opt.py", line 88, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Users\ashlesh\Anaconda3\envs\env_name35\lib\site-packages\theano\gpuarray\dnn.py", line 3866, in apply
    dnn_available.msg)
AssertionError: cuDNN optimization was enabled, but Theano was not able to use it for context None. We got this error:
Device not supported

**Comment by nouiz** [comment]
Your GPU is very old (2014) and not supported by cuDNN. You can tell Theano do not use cudnn by using the Theano flag:
dnn.enabled=False

This should remove thie message. The only other work around is to use a GPU supported by cuDNN. There is nothing else we can do.

This is a Theano issue, not a libgpuarray, so I'll close it. But don't hesitate to reply here.
