### ISSUE TITLE
undefined symbol: GpuKernel_binary

### ISSUE THREAD

**Issue by imk1** [Theano/libgpuarray#588]
I installed libgpuarray and pygpu according to these instructions: http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install-user-library.  When I ran the test at the end, I got the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ikaplow/.local/lib/python2.7/site-packages/pygpu-0.6.5-py2.7-linux-x86_64.egg/pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
ImportError: /home/ikaplow/.local/lib/python2.7/site-packages/pygpu-0.6.5-py2.7-linux-x86_64.egg/pygpu/gpuarray.so: undefined symbol: GpuKernel_binary

Do you know what might be causing this and what I can do to fix it?  Thanks!

**Comment by Foodzo** [comment]
@imk1 
Did you ever solve this issue? I am currently encountering the same problem.

**Comment by imk1** [comment]
If I recall correctly, I solved it by changing my version of cudnn.  I cannot remember how I figured out what version I should use.
